### ISSUE TITLE
Unable to set proxy endpoint

### ISSUE THREAD

**Issue by gesposito** [amplitude/Amplitude-TypeScript#102]
## Expected Behavior
A network request is fired to the custom [apiEndpoint](https://github.com/amplitude/Amplitude-JavaScript/blob/main/src/options.js#L9) url specified with `amplitude.init` config instead of default `https://api2.amplitude.com/2/httpapi`

## Current Behavior
Client fires networks requests to `https://api2.amplitude.com/2/httpapi` regardless of `apiEndpoint` value

```
Type '{ apiEndpoint: string; }' has no properties in common with type 'BrowserOptions'.ts(2559)
```

## Steps to Reproduce

```ts
const amplitudeConfig = {
  apiEndpoint: "www.custom.url",
};
amplitude.init(config.amplitudeAPIKey, undefined, amplitudeConfig);

amplitude.logEvent({
  event_type: eventName,
  event_properties: eventProperties,
});
```

## Environment
- JS SDK Version: 0.4.0
- Installation Method: npm
- Browser and Version: Chrome 101

**Comment by kevinpagtakhan** [comment]
Hey @gesposito, thanks for the feedback. The `apiEndpoint` configuration applies to the [old JS SDK](https://github.com/amplitude/Amplitude-JavaScript). For this new SDK, the configuration is `serverUrl`. Reference here: https://amplitude.github.io/Amplitude-TypeScript/interfaces/Types.BrowserConfig.html#serverUrl

**Comment by gesposito** [comment]
Thanks for the pointer! I'm still unable to make this work, I'll open an updated issue
