### ISSUE TITLE
Unable to set proxy endpoint with `serverUrl`

### ISSUE THREAD

**Issue by gesposito** [amplitude/Amplitude-TypeScript#103]
## Expected Behavior
A network request is fired to the custom [serverUrl](https://github.com/amplitude/Amplitude-JavaScript/blob/main/src/options.js#L9) url specified with `amplitude.init` config instead of default `https://api2.amplitude.com/2/httpapi`

## Current Behavior
Client fires networks requests to `https://api2.amplitude.com/2/httpapi` regardless of `serverUrl` value

<img width="949" alt="Screenshot 2022-05-17 at 11 41 09" src="https://user-images.githubusercontent.com/735227/168781549-354f713d-4c27-4f72-b1b9-e6ac946f381d.png">
<img width="949" alt="Screenshot 2022-05-17 at 11 41 29" src="https://user-images.githubusercontent.com/735227/168781575-b145a7bd-df9b-4165-8faf-3bd62849b13e.png">

## Possible Solution
When creating a config (where `serverUrl`  is read from) we should probably account for the custom `serverUrl` 
https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-core/src/config.ts#L87-L103

## Steps to Reproduce

```ts
const amplitudeConfig = {
  serverUrl: "www.custom.url",
};
amplitude.init(config.amplitudeAPIKey, undefined, amplitudeConfig);

amplitude.logEvent({
  event_type: eventName,
  event_properties: eventProperties,
});
```

## Environment
- JS SDK Version: 0.4.0
- Installation Method: npm
- Browser and Version: Chrome 101

**Comment by kevinpagtakhan** [comment]
@gesposito thanks for submitting this issue. I can confirm this is a bug on our end and we’ll get it fixed soon.

**Comment by kevinpagtakhan** [comment]
@gesposito We've release [v0.4.1](https://www.npmjs.com/package/@amplitude/analytics-browser/v/0.4.1) which contains the fix to this issue. We love hearing feedback from our users on how to make the SDKs better so feel free to drop by again whenever you notice anything else.
