### ISSUE TITLE
Q: onNewSessionStart event

### ISSUE THREAD

**Issue by sutarmin** [amplitude/Amplitude-TypeScript#113]
Hey Amplitude team, thanks for your effort in creating Typescript SDK.

**Question**: is there a way to use [onNewSessionStart](https://amplitude.github.io/Amplitude-JavaScript/#amplitudeclientonnewsessionstart) event/callback using amplitude-ts or should we consider using amplitude-js yet for this functionality?

**Comment by justin-fiedler** [comment]
Hi @sutarmin glad you are liking the new TypeScript SDK.

Unfortunately we don't have session callbacks in the new SDK at this time. I have created a ticket for our team to look into adding support. Hopefully we can add that functionality soon.

**Comment by alexblack** [comment]
I'm also curious about this, with `amplitude-js` we were using the the function `isNewSession` which doesn't seem to be supported any more?

**Comment by sagarsoni7** [comment]
Any considerations on this?

**Comment by jmar777** [comment]
Sorry to wake up a zombie issue, but is there any chance of this being revisited? This callback mechanism seems like the "correct" way to stay apprised of changes to the sessionId, so the inability to access it is quite limiting.
