### ISSUE TITLE
How can this be used with Code Generation with the Ampli CLI

### ISSUE THREAD

**Issue by joelbourbon** [amplitude/Amplitude-TypeScript#114]
Hey guys,

It is pretty unclear if this version of the library can be integrated with the generated code.
I have tried it and never found how to make it work.

Not quite sure I understand the need for this lib, since the ampli generated code is fully typed.

The documentation pushes for this new library, but the implementation guide push towards the amplitude-js lib.

Thanks :)

**Comment by justin-fiedler** [comment]
Hi @joelbourbon thanks for the feedback and sorry for the confusion. 

Currently the generated Ampli SDK is built to work with the Amplitude-JavaScript and Amplitude-Node libraries. We will be releasing a new version of the code generation to work with the new Amplitude-TypeScript library in the near future (next month). 

To see the correct Amplitude SDK to use with Ampli you can:

1. Run `ampli setup` to output the dependencies for Ampli
<img width="558" alt="image" src="https://user-images.githubusercontent.com/5790872/172682807-5e653eef-b4bf-4063-b8ac-0b24ed787823.png">

2. Check the "Implementation" page in the Amplitude Data web UI
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/5790872/172682961-5ca1a06f-a755-40df-ba7f-023957a27640.png">

3. Check the auto-generated header in the generated Ampli SDK files.
https://github.com/amplitude/ampli-examples/blob/main/browser/typescript/react-app/src/ampli/index.ts#L9

Hope this helps!

**Comment by joelbourbon** [comment]
Hey! Thanks for the quick comeback on this @justin-fiedler!

Everything is working fine with the Amplitude-JavaScript version of things.

I'm eager to see the release next month!
Thanks,
