### ISSUE TITLE
How to logout user?

### ISSUE THREAD

**Issue by rafaelquintanilha** [amplitude/Amplitude-TypeScript#115]
Hi there!

The JavaScript API [has a dedicated session to logout and anonymous users](https://developers.amplitude.com/docs/javascript#log-out-and-anonymous-users) where you can `setUserId(null)` when logging out users.

However, this is not present in the new TypeScript docs. [According to the SDK](https://amplitude.github.io/Amplitude-TypeScript/modules.html#setUserId), `setUserId` must receive a string, and therefore passing `null` to this function will generate a TypeScript error.

What's the correct way of logging out users using the TS API?

**Comment by kevinpagtakhan** [comment]
Hi @rafaelquintanilha, thanks for submitting this issue! Good callout. The `userId` is marked is assumed optional in the rest of the code base except as parameter in `setUserId()`. We'll get this updated.
