### ISSUE TITLE
Cannot find name 'Awaited'.

### ISSUE THREAD

**Issue by wangbaiwang** [amplitude/Amplitude-TypeScript#120]
## Expected Behavior
Should not be prompted `Cannot find name 'Awaited'.`

## Current Behavior
![image](https://user-images.githubusercontent.com/46243630/174748057-10da3523-2422-43f2-9860-d526a6cb8608.png)

## Possible Solution
I think that should be Typescript version is too old.

Compatible with 4.5 before Typescript version, please

## Steps to Reproduce
Installed

## Environment
- JS SDK Version: @amplitude/analytics-browser@0.5.1
- Typescript Version: 3.8.3
- Installation Method: Yarn
- Browser and Version: Chrome 102.0.5005.115 (x86_64)

**Comment by kevinpagtakhan** [comment]
Hi @wangbaiwang, thanks for submitting this issue! We'll look into how to support older version of TS!
