### ISSUE TITLE
How to set a proxy

### ISSUE THREAD

**Issue by davidbergso** [amplitude/Amplitude-TypeScript#128]
## Summary

The "apiEndpoint" option does not appear to be working for setting a proxy. Is there a new way to do this with the typescript SDK?

**Comment by dnshi** [comment]
Hi @davidbergso  thanks for submitting this question.

To set a proxy, you can set the option `serverUrl` when you initialize amplitude. 

```js
amplitude.init('API_KEY', 'USER_ID', { serverUrl: "proxy url" });
```

**Comment by otaviojacobi** [comment]
Hello, thanks for the response on this. Just a question, is there any reason why in the typescript API it is called `serverUrl` and in the JS one it is `apiEndpoint`? It seems a bit inconsistent.
