### ISSUE TITLE
Possible race-condition with identify() and logEvent()

### ISSUE THREAD

**Issue by krasnoperov** [amplitude/Amplitude-TypeScript#129]
## Summary

We need to set user's segment with `identify()` and then immediately send entrance event with `logEvent()`. Sometimes at analytics.amplitude.com we see events without any segment at all. Looks like server-side handled identify and logEvent in inverse order, so event has no user properties associated with it.

How it can be avoided? 

Is it possible to combine calls to identify() and logEvent() into one network request, as it works in [AmplitudeNode](https://github.com/amplitude/Amplitude-Node/blob/main/packages/node/src/nodeClient.ts#L90)?

**Comment by kevinpagtakhan** [comment]
Hi @krasnoperov thanks for submitting this question.

Yes, you can combine them in the same event payload to guarantee that they are processed together. You can do this by:

```ts
import { Identify, track } from '@amplitude/analytics-browser';

const identifyObj = new Identify().set('key', 'value');
const event = {
  event_type: 'my-event-type',
  user_properties: identifyObj.getUserProperties(),
};
track(event);
```

The identify class acts as a helper to build the `user_properties` field and `track()` or `logEvent()` accepts an event payload as argument (in addition to string for `event_type`).

An alternate solution is to use `await` on identify call before sending the track event. For example:

```ts
import { Identify, identify, track } from '@amplitude/analytics-browser';

const identifyObj = new Identify().set('key', 'value');
await identify(identifyObj).promise;
track('my-event-type'); // or `await track('my-event-type').promise;`
```

**Comment by krasnoperov** [comment]
Thank you for your help! Both solutions are good for our case!
