### ISSUE TITLE
Option for tracking events before initializing

### ISSUE THREAD

**Issue by yejunlee-29cm** [amplitude/Amplitude-TypeScript#132]
## Summary

Is there any option for tracking events before init?
I am using `next.js` and I'm not 100% sure that the initializing is finished before rendering the app.

**Comment by kevinpagtakhan** [comment]
@yejunlee-29cm thanks for reaching out! currently, init has to complete before any tracking can begin. How are you using amplitude in Next.js? It would be great if you are able to share a simplified code snippet. Not sure if this helps your specific case but `init()` can be awaited like

```ts
await init(API_KEY).promise;
```

**Comment by yejunlee-29cm** [comment]
@kevinpagtakhan  You can see it [here](https://codesandbox.io/s/old-morning-k51ko6?file=/pages/index.js)!

If the app renders before initializing, some events cannot be tracked.

**Comment by liuyang1520** [comment]
@yejunlee-29cm , thanks for providing the example! The issue should be fixed with https://github.com/amplitude/Amplitude-TypeScript/pull/144. We will publish a newer version soon, feel free to try it out then.
