### ISSUE TITLE
Typescript SDK and setVersionName

### ISSUE THREAD

**Issue by FQ400** [amplitude/Amplitude-TypeScript#135]
## Summary

With the JS-SDK we where able to do something like the following to identify the Web-App version:

```
 client.setVersionName(RELEASE_VERSION);
```

What is the equivalent in the Typescript-SDK?

**Comment by kevinpagtakhan** [comment]
Hi @FQ400! Thanks for submitting a question! Is the release version known at time of `init()` call?

With this SDK consuming a [new amplitude analytics HTTP API](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/), this is now referred to as `app_version` in the request [payload](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/#keys-for-the-event-argument). You can assign a value in `init()` call for example:

```ts
amplitude.init(API_KEY, OPTIONAL_USER_ID, {
  appVersion: RELEASE_VERSION,
});
```

**Comment by FQ400** [comment]
Thank you that worked
