### ISSUE TITLE
Calling Identify.set with a null value throws an unhandled exception

### ISSUE THREAD

**Issue by Kyusung4698** [amplitude/Amplitude-TypeScript#136]
## Expected Behavior

```
const user = new Amplitude.Identify();
user.set('key', null) <-- crashes
```

## Current Behavior

Error: Cannot convert undefined or null to object

because: ```typeof null === 'object'```

## Possible Solution

adding || {} to make sure Object.keys doesn't throw
```
export var isValidObject = function (properties) {
    if (Object.keys(properties || {}).length > MAX_PROPERTY_KEYS) {
        return false;
    }
}
```

## Steps to Reproduce

```
const user = new Amplitude.Identify();
user.set('key', null) <-- crashes
```

## Environment
- JS SDK Version: amplitude-ts/1.0.0 
- Installation Method: yarn
- Browser and Version: 87.0.4280

**Comment by kevinpagtakhan** [comment]
Hi @Kyusung4698! Thanks for submitting a GitHub issue! Before I jump into solutioning, I wanted to ask what the motivation of setting an identify key here to `null`? Amplitude offers unsetting an identify key like

```ts
const user = new Amplitude.Identify();
user.unset('key')
```

unless you have a use case for a `null` identify key.

**Comment by Kyusung4698** [comment]
I was integrating amplitude in an existing code base and some fields were based on user settings. So, after pushing to prod I noticed not all users were picked up correctly. The motivation is simply not having an analytics framework throw an error after receiving bad input.

**Comment by kevinpagtakhan** [comment]
@Kyusung4698, I see. We can add a check here to prevent this from throwing an error.
