### ISSUE TITLE
Mistake in the types of parameters of the function `amplitude.getInstance().init()`

### ISSUE THREAD

**Issue by maylorsan** [amplitude/Amplitude-TypeScript#137]
When initializing the amplitude, I want to set the sessionId to the function parameter: 

```
const sessionId = Date.now();
amplitude.getInstance().init(API_KEY, USER_ID, {sessionId});
```

But get the following error: `TS2322: Type 'number' is not assignable to type 'string | null | undefined'.`

Ok... Let's try converting `Date.now()` to string

```
const sessionID = Date.now().toString();
amplitude.getInstance().init(API_KEY, USER_ID, {sessionId});
```

But in the console I have this:

<img width="620" alt="Screen Shot 2022-07-13 at 13 15 41" src="https://user-images.githubusercontent.com/51034456/178710433-ccbe3c3e-782f-4478-a66c-ac6b94d81f8a.png">

## Expected Behavior
Init amplitude with sessionId, whose type: `number`

## Current Behavior
Amplitude inits, but without custom sessionId.

## Possible Solution
Add `@ts-ignore` to this line:

```
const sessionId = Date.now().toString();
amplitude.getInstance().init(API_KEY, USER_ID, {
  // @ts-ignore
  sessionId
});
```

## Steps to Reproduce
1. `npm install amplitude-js`
2. init amplitude with custom sessionID(https://amplitude.github.io/Amplitude-JavaScript/Options/ last param `sessionID`)

## Environment
- JS SDK Version: 8.18.5
- Installation Method: npm
- Browser and Version: Chrome Version 103.0.5060.114

**Comment by justin-fiedler** [comment]
Hi @maylorsan I believe this is an issue with the spelling of `sessionId`. The parameter uses a lower case `d` instead of `D`. Hopefully the following will get things working.

```
const sessionId = Date.now().toString();
amplitude.getInstance().init(API_KEY, USER_ID, {sessionId});
```

**Comment by maylorsan** [comment]
Hi @justin-fiedler 

Sorry, I made a mistake in the description of the problem.(Already updated the this)

Attach the screenshot of my code, and error:

<img width="677" alt="Screen Shot 2022-07-13 at 20 00 29" src="https://user-images.githubusercontent.com/51034456/178789982-aa4abe61-0812-47dc-aaf2-0ebe7c45ad1a.png">

**Comment by kevinpagtakhan** [comment]
@justin-fiedler it appears this issue is for [amplitude-js ](https://github.com/amplitude/Amplitude-JavaScript) so i think the types are coming from definitely typed which has it as `string | null | undefined`

**Comment by justin-fiedler** [comment]
@maylorsan please see Kevin's response above. Although not required we recommend you update to the latest TypeScript SDK for the latest features and bug fixes.

https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/
