### ISSUE TITLE
regenerateDeviceId is not importable

### ISSUE THREAD

**Issue by kykungz** [amplitude/Amplitude-TypeScript#158]
## Expected Behavior

`regenerateDeviceId` should be importable, as it needs to be called on user sign-out event

## Current Behavior

`regenerateDeviceId` is not importable, it is declared in [AmplitudeBrowser](https://github.com/amplitude/Amplitude-TypeScript/blob/d335f6231d6a0bd487824f0ba1dbb92b50793c94/packages/analytics-browser/src/browser-client.ts#L20) class

https://github.com/amplitude/Amplitude-TypeScript/blob/d335f6231d6a0bd487824f0ba1dbb92b50793c94/packages/analytics-browser/src/browser-client.ts#L95-L98

but not being exported in [index.ts](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/index.ts)
https://github.com/amplitude/Amplitude-TypeScript/blob/d335f6231d6a0bd487824f0ba1dbb92b50793c94/packages/analytics-browser/src/index.ts#L1-L20

![Screen Shot 2565-07-29 at 22 07 21](https://user-images.githubusercontent.com/9304909/181789211-5afaed39-7adc-4ac9-b043-afd57670b8e5.png)

So right now I don't have a way to sign users out :(

## Possible Solution

Add `regenerateDeviceId` to exported members of `index.ts`

## Steps to Reproduce

1.
2.
3.
4.

## Environment
- JS SDK Version: 
- Installation Method: 
- Browser and Version:

**Comment by yuhao900914** [comment]
Hi @kykungz,
We are improving the experience of regenerating the deviceId.  We will have another method called `reset`, which will reset the userId and deviceId. It's in progress, and will come soon. 
We will let you know when that comes out. 
Thanks.

**Comment by kykungz** [comment]
@yuhao900914 Thanks, do you have any other solution that I can use when `reset` is not yet available? Or should I revert back to amplitude-js instead.

**Comment by kykungz** [comment]
@yuhao900914 @liuyang1520 Just saw that https://github.com/amplitude/Amplitude-TypeScript/pull/157 was just merged and released an hour ago, that's fast! Thanks a lot!
