### ISSUE TITLE
Validating amplitude has being initialized 

### ISSUE THREAD

**Issue by mperezcorrales** [amplitude/Amplitude-TypeScript#169]
Hello,

I am running amplitude where in some environments we are gonna record tracking and initialize amplitude while on others we are not. Is there a way to validate that amplitude has being initialized without using a try/catch? 
So something like this:
`if (amplitude.isInitialized())...`

**Comment by yuhao900914** [comment]
Hi @mperezcorrales 
Does dose callback work for you in this case? `amplitude.init` is able to return a promise
```
amplitude.init(xxx).promise.then(()=>{
    xxx
}) 
```
