### ISSUE TITLE
EAS Config Plugin for Axpo

### ISSUE THREAD

**Issue by tslater** [amplitude/Amplitude-TypeScript#170]
## Summary
Previously amplitude was a part of Expo Go. Now the standard Expo practice is Config Plugins. As far as I can tell from the docs/code, there is no plugin available.

Here is a link to their guide on config plugins: https://docs.expo.dev/guides/config-plugins/

## Motivations
I want to be able to use EAS build and Amplitude. With the latest release of Expo, we have no way to use Amplitude in our current development environment. We'd have to make big changes to how we develop in order to use Amplitude, so we've quit for now.

**Comment by liuyang1520** [comment]
Hi, @tslater, I just recently learned `expo-analytics-amplitude`. That repo/release is not maintained by Amplitude. Is it possible to switch to our new React-Native SDK: https://github.com/amplitude/Amplitude-TypeScript/tree/main/packages/analytics-react-native?

**Comment by tslater** [comment]
Yeah it worked fine with EAS build and a custom client.
