### ISSUE TITLE
Add documentation about what to do when user logs out

### ISSUE THREAD

**Issue by BrodaNoel** [amplitude/Amplitude-TypeScript#173]
## Summary
It's not clear in the documentation what we have to do when the user "log out".
Should we call `setUserId(null)`? What about the user properties?

I was thinking about doing something like this, but I'm not sure if it will work:

```
setUserId(undefined);

const event = new Identify();
event.remove('username');
event.remove('email');
event.remove('createdAt');
await identify(event);
```

**Comment by kevinpagtakhan** [comment]
Hi @BrodaNoel, thanks for choosing Amplitude!

We offer `reset()` api which creates a new user identity. This is commonly used after user log out as you needed. This basically sets the user ID to `undefined` and assigns a new device ID. The succeeding events after a `reset()` call would no longer share identity with the prior events; therefore, there is no need to remove or unset through identify api.

Reference: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#reset-when-user-logs-out

**Comment by BrodaNoel** [comment]
Fixed on last PR
