### ISSUE TITLE
[docs] Missing docs for `trackingOptions`

### ISSUE THREAD

**Issue by BrodaNoel** [amplitude/Amplitude-TypeScript#176]
## Expected Behavior
There is no documentation about how to disable some trackings.

For example, in the previous library I was using for Amplitude, I had this function:
```
await setTrackingOptionsAsync({
  disableAdid: true,
});
```

Is there a way to disable these options in this library?

## Current Behavior
No docs about it

## Possible Solution
Adding doc (or the feature if missing)

**Comment by liuyang1520** [comment]
Hi, @BrodaNoel , I cannot find any related information about `setTrackingOptionsAsync` method in current SDKs, do you mind sharing the `previous library` version/repo? And the runtime/version you are using for this library?

This library allows custom setup of tracking options, see: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#opt-users-out-of-tracking.

**Comment by BrodaNoel** [comment]
My bad.
I migrated from `https://www.npmjs.com/package/expo-analytics-amplitude` to this component (because Expo SDK 46 doesn't support `expo-analytics-amplitude` anymore.
That library has the `setTrackingOptions` method, which was properly working, so, clearly it's supported by Amplitude

**Comment by BrodaNoel** [comment]
In [the link you sent](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#optional-tracking), I don't see a way to disable the ADID tracking (the old `disableAdid`)

**Comment by liuyang1520** [comment]
I see, thanks for the explanation! Just confirmed that our React-Native SDK (in this repo) doesn't support ADID tracking yet. We will add the ADID tracking in this React-Native SDK.

**Comment by liuyang1520** [comment]
@BrodaNoel , please try @amplitude/analytics-react-native v0.2.3 for disabling the `adid`, I will update the doc there.

**Comment by BrodaNoel** [comment]
@liuyang1520 my problem is that I don't even know how to do it.

I'm currenlty initilizing the library like this:

```js
await initAmplitude(apiKey).promise;
```

At that time, I don't know the user id. What should I do? Something like this?:

```js
await initAmplitude(apiKey, undefined, { adid: false }).promise;
```

**Comment by kevinpagtakhan** [comment]
@BrodaNoel This is how you can disable `adid` tracking:

```ts
const trackingOptions = {
  adid: false,
};
await init(API_KEY, undefined, { trackingOptions }).promise;
```

We'll formally add this to our developer docs pretty soon.

**Comment by BrodaNoel** [comment]
Done! I just implemented it and releasing in few minutes.

We can keep the issue open until you fix the docs. Feel free to close it at that moment!

Thanks for the work people!

**Comment by kevinpagtakhan** [comment]
The docs can be found here: https://www.docs.developers.amplitude.com/data/sdks/react-native-sdk/#optional-tracking

**Comment by justin-fiedler** [comment]
New link (the one above is broken):
https://www.docs.developers.amplitude.com/data/sdks/typescript-react-native/#optional-tracking
