### ISSUE TITLE
Different `platform` values

### ISSUE THREAD

**Issue by BrodaNoel** [amplitude/Amplitude-TypeScript#177]
After migrating from `expo-analytics-amplitude` (which uses Amplitude-ReactNative) to this library, I'm seeing different values in the Platform:
<img width="877" alt="Screen Shot 2022-08-09 at 15 15 59" src="https://user-images.githubusercontent.com/1837969/183730580-8aff0ff9-f3a2-4552-9f9a-faf11c5a1370.png">

As you can see, there is an `Android` and an `android`, which breaks all the charts.

You may want to consider defining an standard between your libraries, in order to avoid this.

**Comment by liuyang1520** [comment]
Hi, @BrodaNoel , thanks for reporting!

I took a look at our libs, and found that we are consistent about the OS name attribute, see list:
- This new RN lib: https://github.com/amplitude/Amplitude-TypeScript/blob/7d11fdbee2ece65b64cec873d2f2ab74ed5fecf3/packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/AndroidContextProvider.kt#L404
- The new Android Kotlin SDK: https://github.com/amplitude/Amplitude-Kotlin/blob/8c46250e3ee957e22f97ad5d6e957e12ebe82272/common-android/src/main/java/com/amplitude/common/android/AndroidContextProvider.kt#L406
- Amplitude-Android SDK (used by `expo-analytics-amplitude`, not familiar with this, as this is not the official one, so not maintained by us, but I saw they mention this SDK in the readme. I don't think they are using `Amplitude-ReactNative`, see https://github.com/expo/expo-analytics-amplitude): https://github.com/amplitude/Amplitude-Android/blob/main/src/main/java/com/amplitude/api/DeviceInfo.java#L31

Could you provide more information about
1. which even property
2. any customization of this value
3. ways to reproduce/setup
4. any sample raw event (remove personal information) would be helpful here

**Comment by BrodaNoel** [comment]
That's weird... They say they wrap here https://github.com/expo/expo/tree/sdk-45/packages/expo-analytics-amplitude#expo-analytics-amplitude

> Provides access to Amplitude (https://amplitude.com/) mobile analytics. This module wraps Amplitude-iOS (https://github.com/amplitude/Amplitude-iOS) and Android (https://github.com/amplitude/Amplitude-Android) SDKs.

<img width="1225" alt="Screen Shot 2022-08-10 at 00 38 45" src="https://user-images.githubusercontent.com/1837969/183807843-d2081981-bac0-4940-b3ba-792c33a5755a.png">

Here some raw data:


For `android`:
```
{
  "$insert_id": "103a5a47-6cd0-49ce-ac75-f3abca39e71b",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660082377396,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 277612122939,
  "app": 227935,
  "city": "xxx", // removed
  "client_event_time": "2022-08-09 21:59:37.396000",
  "client_upload_time": "2022-08-09 21:59:38.504000",
  "country": "Germany",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": null,
  "device_carrier": "vodafone.de",
  "device_family": "Samsung Galaxy Phone",
  "device_id": "xxx", // removed
  "device_manufacturer": "samsung",
  "device_model": "SM-G985F",
  "device_type": "Samsung Galaxy S20+",
  "display_name": "Mark as Visited",
  "dma": null,
  "event_id": 86,
  "event_properties": {
  },
  "event_time": "2022-08-09 21:59:37.396000",
  "event_type": "EVENT_SPOT_CHECKIN",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": "xxx", // removed
  "is_attribution_event": false,
  "language": "German",
  "library": "amplitude-react-native-ts/0.2.1",
  "location_lat": null,
  "location_lng": null,
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "android",
  "region": "xxx", // removed
  "sample_rate": null,
  "server_received_time": "2022-08-09 21:59:38.504000",
  "server_upload_time": "2022-08-09 21:59:38.508000",
  "session_id": 1660081715041,
  "start_version": "10.4.0",
  "timeline_hidden": false,
  "user_creation_time": "2021-07-10 09:09:00.543000",
  "user_id": "xxx", // removed
  "user_properties": {
    // removed
  },
  "uuid": "", // removed
  "version_name": "13.28.1"
}
```

For `Android`:
```
{
  "$insert_id": "3e20043c-2e5e-4c6b-91d5-a9dbfbac3ce8",
  "$row_source": "realtime",
  "$schema": 12,
  "_time": 1660074543387,
  "adid": null,
  "amplitude_attribution_ids": null,
  "amplitude_event_type": null,
  "amplitude_id": 233462445261,
  "app": 227935,
  "city": "Kirchhain",
  "client_event_time": "2022-08-09 19:49:05.142000",
  "client_upload_time": "2022-08-09 19:49:35.205000",
  "country": "Germany",
  "data": {
    "group_first_event": {
    },
    "group_ids": {
    }
  },
  "device_brand": "google",
  "device_carrier": "vodafone.de",
  "device_family": "Google Phone",
  "device_id": "311f52e4-8a9e-40b2-9e8b-a2d0e9a8a82eR",
  "device_manufacturer": "Google",
  "device_model": "Pixel 6",
  "device_type": "Google Pixel 6",
  "display_name": "Open Spot",
  "dma": null,
  "event_id": 127,
  "event_properties": {
    "spotId": "f244895d-2c12-4c40-b4fb-8bc046badcf4"
  },
  "event_time": "2022-08-09 19:49:03.387000",
  "event_type": "MODAL_SPOT",
  "group_properties": {
  },
  "groups": {
  },
  "idfa": null,
  "ip_address": "adsads", //removed
  "is_attribution_event": false,
  "language": "German",
  "library": "amplitude-android/2.23.2",
  "location_lat": 123123, //removed
  "location_lng": 123123,v
  "os": "android 12",
  "os_name": "android",
  "os_version": "12",
  "partner_id": null,
  "paying": null,
  "plan": {
  },
  "platform": "Android",
  "region": "Hesse",
  "sample_rate": null,
  "server_received_time": "2022-08-09 19:49:33.450000",
  "server_upload_time": "2022-08-09 19:49:33.454000",
  "session_id": 1660074498318,
  "start_version": "9.0.2",
  "timeline_hidden": false,
  "user_creation_time": "2021-02-12 06:45:21.401000",
  "user_id": "xxx", //removed
  "user_properties": {
     //removed
  },
  "uuid": "xxx", //removed
  "version_name": "13.30.0"
}
```

**Comment by BrodaNoel** [comment]
This is my whole REAL code that I use to track everything with this library:

As you can see, I don't change anything related to the Platform value

```js
import {
  identify,
  Identify,
  setUserId as setUserIdAmplitude,
  init as initAmplitude,
  track as trackEvent,
  reset,
} from '@amplitude/analytics-react-native';
import * as Sentry from 'sentry-expo';
import config from '../config';

// eslint-disable-next-line no-undef
const isProduction = !__DEV__;

let wasInited = false;

const init = async () => {
  try {
    const apiKey = isProduction ? config.amplitude.apiKey.production : config.amplitude.apiKey.dev;

    await initAmplitude(apiKey).promise;

    // TODO: Missing since the migration from `expo-analytics-amplitude` to `@amplitude/analytics-react-native`
    // await setTrackingOptionsAsync({
    //   disableAdid: true,
    // });
    wasInited = true;
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

const setUserId = async user => {
  try {
    if (!wasInited) {
      await init();
    }

    await setUserIdAmplitude(user.id);

    const event = new Identify();
    event.set('username', user.username);
    event.set('createdAt', user.createdAt);

    if (user.email) {
      event.set('email', user.email);
    }

    await identify(event).promise;
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

const clear = async () => {
  try {
    if (!wasInited) {
      await init();
    }

    reset();
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

const track = async (eventName, properties) => {
  try {
    if (!wasInited) {
      await init();
    }

    if (properties) {
      trackEvent(eventName, properties);
    } else {
      trackEvent(eventName);
    }
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

export default {
  init,
  setUserId,
  clear,
  track,
};
```

**Comment by liuyang1520** [comment]
Thanks for sharing! I see. So the diff is actually for the `platform` field, not the `os_name` field. To unblock you, could you try to group by `OS` property? I will take a look at why the `platform` is different here.

**Comment by BrodaNoel** [comment]
Grouped by OS will get a bit crazy:

<img width="1170" alt="Screen Shot 2022-08-10 at 01 07 39" src="https://user-images.githubusercontent.com/1837969/183811850-5fd315da-fb74-4790-bf18-03fa0b33db76.png">

If you need some real project to test (in case you have access to internal data), my project is `nofilter` (https://getnofilter.com , but the tracking if for the app, no the web)

**Comment by BrodaNoel** [comment]
@liuyang1520 Important: https://github.com/amplitude/Amplitude-Android/blob/e0c9cc90d1f1f49c62ed6b35ae09936f5eb53d72/src/main/java/com/amplitude/api/Constants.java#L11

**Comment by liuyang1520** [comment]
@BrodaNoel , yeah, for `platform` property (not `os_name`), we have this inconsistency between the SDK and React-Native. Will find a solution for this.

**Comment by liuyang1520** [comment]
@BrodaNoel , please try @amplitude/analytics-react-native v0.2.3.

**Comment by BrodaNoel** [comment]
I'll take a look soon.
I'll let you know if this gets fixed

**Comment by BrodaNoel** [comment]
I just made a new build and released it.
I'll wait for some users to use it, and see how it works.

**Comment by BrodaNoel** [comment]
`Android` going up again, and `android` going down.
Seems to be fixed! Good job!

<img width="814" alt="Screen Shot 2022-08-14 at 14 40 16" src="https://user-images.githubusercontent.com/1837969/184548511-4c361c0c-e93d-439e-ae26-5df6c3d2326b.png">
