### ISSUE TITLE
undefined is not an object (evaluating 'this.config.loggerProvider')

### ISSUE THREAD

**Issue by ahilles107** [amplitude/Amplitude-TypeScript#185]
## Expected Behavior
Events are logged without errors. 

## Current Behavior
Crashed in non-app: node_modules/@amplitude/analytics-types/lib/config.js in SpecialEventType

## Possible Solution
none

## Steps to Reproduce
import { init as amplitudeInit, track } from "@amplitude/analytics-react-native";
amplitudeInit("xxxxxxxx");

track(eventName);

## Environment
- expo 46 / react native

```
"@amplitude/analytics-connector@1.4.5":
  version "1.4.5"
  resolved "https://registry.npmjs.org/@amplitude/analytics-connector/-/analytics-connector-1.4.5.tgz#07e9375101332bd8b6f15e39e70f31f287e87ad0"
  integrity sha512-ELAP6ivg+13uSk+TOirGZE/92M+tTbeiQ/i7eXgDO4Hiy00Abf/UxO/rp9WovtxCyeFYTILrujEYxPv5cRQmFw==
  dependencies:
    "@amplitude/ua-parser-js" "0.7.31"

"@amplitude/analytics-core@^0.6.4":
  version "0.6.4"
  resolved "https://registry.npmjs.org/@amplitude/analytics-core/-/analytics-core-0.6.4.tgz#510c31de9ee06a1178ec3898435f8d026af49f30"
  integrity sha512-RuWkLGO89O/8x88J7OPMIB1sSZ+toAJQeEI+KFkZGU1uQ0znhF1nLe64UUi39mP7qLMFYtQfXVD8IfNLIJt7IQ==
  dependencies:
    "@amplitude/analytics-types" "^0.6.1"
    tslib "^2.3.1"

"@amplitude/analytics-react-native@^0.2.0":
  version "0.2.1"
  resolved "https://registry.npmjs.org/@amplitude/analytics-react-native/-/analytics-react-native-0.2.1.tgz#cdb7c5ddb16fc0085e1c4f3d00a72247a30c3228"
  integrity sha512-9Cvascq1XpkvNPzMDdh90qKaeDILZD9E99M/nI+x4VjHUW0f+ytoDTuOcTG5ItO8baEmY2xBMu5UgTPSPnu33g==
  dependencies:
    "@amplitude/analytics-connector" "1.4.5"
    "@amplitude/analytics-core" "^0.6.4"
    "@amplitude/analytics-types" "^0.6.1"
    "@amplitude/ua-parser-js" "^0.7.31"
    "@react-native-async-storage/async-storage" "^1.17.7"
    tslib "^2.3.1"

"@amplitude/analytics-types@^0.6.1":
  version "0.6.1"
  resolved "https://registry.npmjs.org/@amplitude/analytics-types/-/analytics-types-0.6.1.tgz#bd12255f33f7a396b61924d11e6d0e7fe8152ba2"
  integrity sha512-6XWxxt0LYMkOLZHnAzLoDRwhMcOeNviXEdba6tVVjYOM9zW6ZOCLZWO3N+/s+UF6tYOvDZyLH6a1PqAlNUvHqQ==

"@amplitude/ua-parser-js@0.7.31", "@amplitude/ua-parser-js@^0.7.31":
  version "0.7.31"
  resolved "https://registry.npmjs.org/@amplitude/ua-parser-js/-/ua-parser-js-0.7.31.tgz#749bf7cb633cfcc7ff3c10805bad7c5f6fbdbc61"
  integrity sha512-+z8UGRaj13Pt5NDzOnkTBy49HE2CX64jeL0ArB86HAtilpnfkPB7oqkigN7Lf2LxscMg4QhFD7mmCfedh3rqTg==
```

**Comment by kevinpagtakhan** [comment]
Hi @ahilles107, thanks for choosing Amplitude! This was a known issue but has been fixed. Looking at the versions you have in your lock file, I do not expect this issue to show up anymore.

I have created an expo app here: https://github.com/kevinpagtakhan/TS-185 to try to reproduce the error you are seeing, [specifying the same amplitude dependencies in my lock file](https://github.com/kevinpagtakhan/TS-185/blob/main/yarn.lock#L5-L40) and added calls to amplitude in [App.js](https://github.com/kevinpagtakhan/TS-185/blob/main/App.js#L5-L6). I am not able to reproduce the issue.

Is it possible that you recently upgraded to the specified version and the old version was somehow still cached and being loaded onto your app? I am able to reproduce the error in an older version.

In addition, we also have released more patch versions for `@amplitude/analytics-react-native` and it would be best to bump up to get the latest and greatest.

**Comment by liuyang1520** [comment]
@ahilles107 , thanks for reporting this! Based on @kevinpagtakhan 's investigation, could you try a fresh install of latest `@amplitude/analytics-react-native`, clear caches, and run expo with `--clear`? See https://docs.expo.dev/troubleshooting/clear-cache-macos-linux/.

**Comment by ahilles107** [comment]
Hey folks! You are right, sorry for the trouble. An error was caught by Sentry on a production where we have older versions of libraries installed. After deps upgrade, I can't reproduce it anymore.
