### ISSUE TITLE
Cookie-related options should be passed to `testStorage` in `CookieStorage.isEnabled()`

### ISSUE THREAD

**Issue by nckcol** [amplitude/Amplitude-TypeScript#194]
Amplitude options `cookieSameSite` and `cookieSecure` has direct influence on cookie availability. For example Chrome do not accept third-party cookies without explicit `SameSite=None; Secure`. And therefore `new CookieStorage({ sameSite: true, secure: true, }).isEnabled()` returns `false` despite real ability to use cookies.

## Expected Behavior
When passing this cookie options amplitude should be able to use `CookieStorage` in third-party context
```
amplitude.init(AMPLITUDE_API_KEY, undefined, {
  cookieSameSite: "None",
  cookieSecure: true,
});
```

## Current Behavior
`CookieStorage` is not used because of incorrect test for cookie availability

## Possible Solution
Pass at least `secure` and `sameSite` parameters from `this.options` when creating `testStorage`

## Steps to Reproduce
1. Init amplitude with `cookieSameSite: "None"` and `cookieSecure: true`
2. Open tracked page in `iframe` from page with different origin

## Environment
- JS SDK Version: `@amplitude/analytics-browser@1.1.4`
- Installation Method: pnpm
- Browser and Version: Google Chrome Version 104.0.5112.79 (Official Build) (64-bit)

I can provide more information if needed.
Thank you and have a nice day :slightly_smiling_face:

**Comment by kevinpagtakhan** [comment]
Hi @nckcol, thank you for using Amplitude. Before I jump into solutioning, I'd love to hear more info. From a business standpoint, what use case is this preventing you to do? And with the proposed fix, what is the use case it allows you to fulfill? Thanks so much!

**Comment by nckcol** [comment]
Hello, @kevinpagtakhan!

I have website with embedded `iframe` widgets. Users can go from the widget to my website. And I track events both in this widgets and on the website. With default amplitude configuration in `iframe` widget it fails to check `CookieStorage` availability because of third-party context and fallbacks to using `LocalStorage`. But on the website it uses `CookieStorage` like it should. Therefore same user in the same browser is tracked as users from different devices. This for example prevents to build funnel for how many users came to the website through the widget.

With `SameSite: None; Secure` browser allows to use same cookies in third-party context as on the website, so user events from widget and from site can be determined as from same user (device). But `CookieStorage.isEnabled()` check fails anyway despite any cookie configuration, because it uses default options for `testStorage`.

For now i bypass this problem with disabling cookies and as a result using `LocalStorage` everywhere. But this solution is not ideal because tracking information (device id for ex.) only available on the browser-side of application. And i can't use this information for server-side tracking.

Thank you for your time! Good luck!

**Comment by bohan-amplitude** [comment]
Hi @nckcol I added a fix for this issue in the new [@amplitude/analytics-browser@1.2.1](https://github.com/amplitude/Amplitude-TypeScript/releases/tag/%40amplitude%2Fanalytics-browser%401.2.1) and [@amplitude/analytics-react-native@0.3.1](https://github.com/amplitude/Amplitude-TypeScript/releases/tag/%40amplitude%2Fanalytics-react-native%400.3.1). Please check and let me know if you have other questions

**Comment by kevinpagtakhan** [comment]
Good to hear, @nckcol. Thank you for your contribution!
