### ISSUE TITLE
[react-native] Duplicated users

### ISSUE THREAD

**Issue by BrodaNoel** [amplitude/Amplitude-TypeScript#195]
Here I am again with new updates after https://github.com/amplitude/Amplitude-TypeScript/issues/178

It seems like even calling `init` only 1 time, it keeps duplicating the users.

Let me show you what I did these days:

Yesterday, I upgraded to the last version (`"@amplitude/analytics-react-native": "^0.2.3",`), and implemented [the fix](https://github.com/amplitude/Amplitude-TypeScript/issues/179#issuecomment-1216973642) for the missing "Version".

After that, I checked the Amplitude dashboard and I see that my last app release (which contains the fix), is still duplicating users.

The weird thing, is that now I am only calling 1 time the `init` function.

This is the REAL code I have:

```js
// App.js file. The main file.

class App extends Component {
  async componentDidMount() {
      await this.loadBasicStuff();
  }

  loadBasicStuff = async () => {
    try {
      const proms = [
        Asset.fromModule(require('./src/styles/imgs/splash-screen-ph.png')).downloadAsync().catch(() => {}), // just loading a splash photo
        actions.analytics.init(), // <<<< HERE THE IMPORTANT! I am calling only 1 time this `init` function
      ];

      await Promise.all(proms); // Here I wait for those 2 promises to get resolved.

      actions.analytics.track('APP_OPEN'); // Here I call my first Amplitude event.

      await SplashScreen.hideAsync(); // other unrelated stuff
    } catch (error) {
      Sentry.Native.captureException(error);
    }
  };
```

As you can see, I have 2 important functions: `actions.analytics.init` and `actions.analytics.track`.
Let's see the code for both of them:

```js
import {
  identify,
  Identify,
  setUserId as setUserIdAmplitude,
  init as initAmplitude,
  track as trackEvent,
  reset,
} from '@amplitude/analytics-react-native';
import * as Sentry from 'sentry-expo';
import Constants from 'expo-constants';
import config from '../config';

const isProduction = !__DEV__;

const init = async () => {
  try {
    const apiKey = isProduction ? config.amplitude.apiKey.production : config.amplitude.apiKey.dev;

    await initAmplitude(apiKey, undefined, {
      appVersion: Constants.manifest.version,
      trackingOptions: {
        adid: false,
      },
    }).promise;
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

const setUserId = async user => {
  try {
    await setUserIdAmplitude(user.id);

    const event = new Identify();
    event.set('username', user.username);
    event.set('createdAt', user.createdAt);

    if (user.email) {
      event.set('email', user.email);
    }

    await identify(event).promise;
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

const track = async (eventName, properties) => {
  try {
    if (properties) {
      trackEvent(eventName, properties);
    } else {
      trackEvent(eventName);
    }
  } catch (error) {
    Sentry.Native.captureException(error);
  }
};

export default {
  init,
  setUserId,
  track,
};

```

As you can see there, in the `init` function, I'm initializing Amplitude with this:

```js
    await initAmplitude(apiKey, undefined, {
      appVersion: Constants.manifest.version,
      trackingOptions: {
        adid: false,
      },
    }).promise;
```
So, if that works as I imagine, the `await` should force the `init` function to not be solved until the initialization is totally done. So after that, the `await Promise.all(proms);` in the `App.js` file will be solved, and THEEEN, the next `actions.analytics.track('APP_OPEN');` should be made with the mentioned initialization.

The problem is that some milliseconds after, I'm calling `actions.analytics.track('GO_TO_EXPLORE_PAGE')`, and that new event is tracked with other device id, and the followings events will be tracked with this one, resulting on `APP_OPEN` event being tracked with the first device id, and then all the other events with other device id.

As you can see here:

<img width="910" alt="Screen Shot 2022-08-17 at 15 15 47" src="https://user-images.githubusercontent.com/1837969/185212923-51b51c51-15cc-4eaf-a073-77d5b69b075f.png">

<img width="904" alt="Screen Shot 2022-08-17 at 15 16 09" src="https://user-images.githubusercontent.com/1837969/185212987-88d94a63-5a9c-445f-8c91-8e0776e7af8f.png">

So... To sum up:
IF FEELS LIKE the `init` function is being called 2 times but I am actually only calling it 1 time (because of the `await Promise.all()`).

This seems to be a simple issue, but creating duplicated users is killing all the Retention Metrics (the most important ones) :(

**Comment by BrodaNoel** [comment]
I have the feeling that the error of all this stuff, is that the `init` Amplitude function is resolving the `promise` before it actually finished the whole work.

So, this may not be working well:

```js
    await initAmplitude(apiKey, undefined, {
      appVersion: Constants.manifest.version,
      trackingOptions: {
        adid: false,
      },
    }).promise; // <<< This promise may be solved before the device id was created, or something like that.
```

**Comment by kevinpagtakhan** [comment]
Hi @BrodaNoel, Amplitude SDK should generate a new device ID on `init()` call. We've recently added a feature that allows `track()` to be called before or during `init()` as if it had awaited `init()` or "deferred init". Are you open to calling `init()` at the top level of your root component file? For example:

```ts
initAmplitude();

class App extends Component {}
```

With "deferred init" feature, you should not need to await on init, therefore can be called at the top level. Reason here is it guarantees that it will only be called once, rather than putting it in react lifecycle where components may mount/unmount leading to multiple calls.

On top of this, the latest version of the SDK prevents concurrent `init` calls to handle unintended multiple calls of `init`. Serially calling `init` is not blocked.

**Comment by BrodaNoel** [comment]
Seems like this is good to close with the deferred init.
I implanted it some days ago and now the amount of new users seems to be correct
