### ISSUE TITLE
`setUserId(undefined)` should be allowed

### ISSUE THREAD

**Issue by sod** [amplitude/Amplitude-TypeScript#218]
The `reset` function does `setUserId(undefined)`:
https://github.com/amplitude/Amplitude-TypeScript/blob/6294f2fd4578e5184dec5a707f3162cbe83119e6/packages/analytics-browser/src/browser-client.ts#L118-L121

The method `setUserId` allows `undefined`:
https://github.com/amplitude/Amplitude-TypeScript/blob/6294f2fd4578e5184dec5a707f3162cbe83119e6/packages/analytics-browser/src/browser-client.ts#L98

But the web-client typings prohibit undefined:
https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/client/web-client.ts#L23

Please change it to `setUserId(userId: string | undefined)` as well

**Comment by kevinpagtakhan** [comment]
if you're using the browser package, this is release as part of `@amplitude/analytics-browser@1.4.0`.

**Comment by sod** [comment]
Thank you :)
