### ISSUE TITLE
setUserId function signature mismatch 

### ISSUE THREAD

**Issue by BeepYoung** [amplitude/Amplitude-TypeScript#221]
## Expected Behavior
I except signature of setUserId includes undefined type to set anonymous user
```
...
setUserId: (userId: string | undefined) => void
...
```

## Current Behavior

https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/browser-client.ts#L104 signature mismatch with exported function type
I have this stuff in @amplitude/analytics-browser/lib/esm/index.d.ts 
```
...
setUserId: (userId: string) => void
...
```

## Steps to Reproduce

1. install "@amplitude/analytics-browser": "^1.3.0"
2. look at @amplitude/analytics-browser/lib/esm/index.d.ts

## Environment
- Installation Method: npm i

**Comment by kevinpagtakhan** [comment]
Thank you for choosing Amplitude! The fix to this issue was merged yesterday. We'll be kicking off a release shortly.

**Comment by kevinpagtakhan** [comment]
if you're using the browser package, this is release as part of `@amplitude/analytics-browser@1.4.0`.

**Comment by BeepYoung** [comment]
@kevinpagtakhan thank you for support!
