### ISSUE TITLE
`init()` function throws Unhandled Rejection TypeError when API KEY is missing

### ISSUE THREAD

**Issue by pitahorn** [amplitude/Amplitude-TypeScript#238]
Hi,

We encountered an issue while working with the package on a dev environment. We wanted Amplitude to track events in production only, so in development and staging environments the Amplitude API KEY would not be provided. We wrapped this logic in a `try/catch` sequence, but it throws an Unhandled Rejection TypeError nevertheless.

Function call on our code:
```js
/**
 * Initialize Amplitude / Google Analytics / Facebook Pixel / etc
 */
export function InitializeTrackers() {
  try {
    init(process.env.REACT_APP_AMPLITUDE_KEY);  // <--- Not provided on development or staging
  } catch (e) {
    console.log('Failed to load amplitude analytics', e);
  }
}
```

## Expected Behavior
The error should be handled downstream.

## Current Behavior
The error seems to be coming from this return in `src/cookie-name.ts:8`: 
```
return `${AMPLITUDE_PREFIX.toLowerCase()}_${apiKey.substring(0, 6)}`;
```
Since apiKey is not provided, the substring is problematic.
<img width="1042" alt="image" src="https://user-images.githubusercontent.com/26127375/193128417-b51ef81c-5387-4507-84cf-1f1b54461268.png">

## Possible Solution
- Having a fallback base value for apiKey so the error can be avoided.

## Steps to Reproduce
We are using a CRA app with TypeScript (^4.3.5) and React (^17.0.2),
1. Install the `@amplitude/analytics-browser` package on your project.
3. Import the `init()` method in your main App. 
4. Initialize with a potentially undefined value:
    ```js
    import { init } from '@amplitude/analytics-browser';
    // ... 
    const API_KEY = process.env.REACT_APP_AMPLITUDE_KEY;
    try {
        init(API_KEY);
    } catch(e) {
        console.log('Amplitude not available', e);
    }
    ```
6. Load your app and watch Unhandled Rejection TypeError mentioned above.

## Environment
- JS SDK Version: `node: >=16.0.0`
- Installation Method: yarn 
- `@amplitude/analytics-browser@^1.4.0`
- Browser and Version: Chrome 105.0.5195.125 (Official Build) (arm64)

Thanks! 👋🏼

**Comment by liuyang1520** [comment]
Hi, @pitahorn ,

Thanks for reporting this! I think this issue can be solved with:
```javascript
export function InitializeTrackers() {
  try {
    init(process.env.REACT_APP_AMPLITUDE_KEY || "DEV_API_KEY");  // add any default value when API key doesn't exist
  } catch (e) {
    console.log('Failed to load amplitude analytics', e);
  }
}
```

Another way is you can create the dev environment project in Amplitude, so when you are developing things, can verify the events in the dev environment in Amplitude. The API keys are seperated.

I think we should handle the issue in `src/cookie-name.ts:8` though, I will create a PR to fix it.

Thanks!

**Comment by liuyang1520** [comment]
Merged and released in https://www.npmjs.com/package/@amplitude/analytics-browser/v/1.5.2, thank you!

**Comment by pitahorn** [comment]
Wow, that was fast! Thanks for the quick support 🥇
