### ISSUE TITLE
Web attributions are not set on events tracked before init

### ISSUE THREAD

**Issue by jpreynat** [amplitude/Amplitude-TypeScript#246]
## Expected Behavior
When using the `@amplitude/analytics-browser` module, all events sent with `track` before calling the `init` method should have the web attribution properties.

## Current Behavior
Currently, whenever calls to `track` are made previous to the initialization are sent to Amplitude when `init` is called, but the call to `$identify` assigning the web attributions to the user properties is only made **after** those initial events are sent.

Here is an example of what's happening in the calls to the API:
![image](https://user-images.githubusercontent.com/7927876/194319005-c971407a-fb4e-489e-a10e-97516cef3c19.png)

We can see that the `$identify` event is only sent second, after a first custom event has been sent.

This results in unreconciled events and web attributions in the initial event:

![image](https://user-images.githubusercontent.com/7927876/194319399-542c2c7d-8719-4bfc-9b76-1a6f93b77895.png)

While subsequent events tracked (post-`init`) do have these properties:

![image](https://user-images.githubusercontent.com/7927876/194319533-c51ec09d-78db-4b40-963b-cfd8b7336177.png)

This means that it's impossible to actually track web attributions on initial events happening on our website.

Additionally, it's expected most of the times to track only on event such as a page view initially, before a user is navigating to another website. If no other event is sent to Amplitude in the meantime, it becomes impossible to use the UTM tracking and other web attributions.

## Possible Solution

I believe that the issue relies in the `init` method for the `AmplitudeBrowser` class.
At [this line](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/browser-client.ts#L39), we are calling the `AmplitudeCore` `_init` method, that will [deliver all the previously queued events](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-core/src/core-client.ts#L43-L45).

The identify call is made only after all these events have been flushed, [at the end of the `init` function](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/browser-client.ts#L82).

## Steps to Reproduce

1. Create a simple web page and `track` an event at page load and call `init` of the client
2. Access the web page with utm parameters
3. The initial event won't have web attributions attached

## Environment
- JS SDK Version: @amplitude/analytics-browser@1.5.3
- Installation Method: `import`
- Browser and Version: Chrome 106

**Comment by bohan-amplitude** [comment]
Hi @jpreynat Thank you for submitting. I'll look into this issue.

**Comment by kevinpagtakhan** [comment]
Hi @jpreynat thanks for choosing Amplitude. Great observations above! I agree this is an issue. We'll rethink where we invoke the queued functions: https://github.com/amplitude/Amplitude-TypeScript/blob/578cbe218de84d7fdd4930f75820beda6f85ce6d/packages/analytics-core/src/core-client.ts#L41-L45 around.

**Comment by remigu** [comment]
Friendly bump: any chance you could share an ETA so we can act on it 🙏 
Thank you!

**Comment by justin-fiedler** [comment]
Hi @remigu we are actively looking at this and hope to have a solution soon. I will get back to you tomorrow with an update.

**Comment by justin-fiedler** [comment]
I am still investigating a real fix but a simple potential fix would be to wait until after `init()` has completed before tracking events. I am guessing you may have already considered this and it may not be possible given your setup. Still thought I'd mention it incase it helps.

```
// wait for init to complete before continuing
await amplitude.init('API_KEY')

// track events after init
track('My Event with attribution')
```

**Comment by justin-fiedler** [comment]
We made progress on this today. Hoping to have a fix by the end of the week.

**Comment by jpreynat** [comment]
Thanks for the fix and the ping @justin-fiedler, we'll give it a try asap and let you know 🙂

**Comment by remigu** [comment]
HI @justin-fiedler, thank you for the update.
We tested it in staging but looks like it doesn't work.

Please find here an example:
You can see the UTM in the URL but the user properties are unset at the event level
<img width="1098" alt="Screenshot 2022-10-17 at 09 59 54" src="https://user-images.githubusercontent.com/32708670/196123230-8afbb35a-76f6-43b1-9946-0d2ce8c96bd8.png">


But set at the user properties level, which means we still have 1 page latency on attribution
<img width="368" alt="Screenshot 2022-10-17 at 10 05 11" src="https://user-images.githubusercontent.com/32708670/196123188-10598114-e1f1-4ee1-ae25-440db24733e3.png">

In the console, we see the identify being sent after the 1st event (and you can see the library used)
<img width="400" alt="Screenshot 2022-10-17 at 10 09 09" src="https://user-images.githubusercontent.com/32708670/196123803-9bfff3ba-0d1a-4737-9edf-6a96c0a65c41.png">


Hope it helps

**Comment by kevinpagtakhan** [comment]
Hi @jpreynat, we took another try here. We just merged the fix and we'll kick off a release shortly.

**Comment by jpreynat** [comment]
Hi @kevinpagtakhan, thanks for the update.
We’ll give it a try once this has been released 👍

**Comment by kevinpagtakhan** [comment]
We have [@amplitude/analytics-browser@1.5.6](https://www.npmjs.com/package/@amplitude/analytics-browser/v/1.5.6) now available 🎉
