### ISSUE TITLE
TypeError: Cannot read property 'search' of undefined in React Native

### ISSUE THREAD

**Issue by johnf** [amplitude/Amplitude-TypeScript#257]
## Expected Behavior
No unexpected promises

## Current Behavior
I'm seeing the following error

```
WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: Cannot read property 'search' of undefined
TypeError: Cannot read property 'search' of undefined
    at getQueryParams (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false&app=com.gladlyapp.mobile.debug&modulesOnly=false&runModule=true:143590:89)
```

## Possible Solution
In https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-client-common/src/query-params.ts#L6
```
if (!globalScope?.location.search) {
    return {};
}
```
Needs to be ```globalScope?.location?.search``` note the second ```?```

## Steps to Reproduce
Initialise the library in a react-native app with the current version
 ```
"@amplitude/analytics-react-native": "^0.4.6",
 "@amplitude/analytics-browser": "^1.5.5",
```

## Environment
- JS SDK Version: As above
- Installation Method: Yarn and import 
- Browser and Version: React Native 0.70.4

**Comment by hatem-72** [comment]
Adding to this, I noticed strange release versioning for RN plugin. Version `4.9.0` being released after version `4.10.0` 🧐
![image](https://user-images.githubusercontent.com/86654761/198035068-4190f403-4622-49d2-b3a0-5c28c61623d2.png)

**Comment by kevinpagtakhan** [comment]
Hi @johnf thank you for letting us know. I opened a PR to fix the issue. On a side note, just being generally curious, I wanted to learn more about your setup. I saw you are importing both `@amplitude/analytics-react-native` and `@amplitude/analytics-browser`. Are these being used for the same project?

**Comment by kevinpagtakhan** [comment]
> Adding to this, I noticed strange release versioning for RN plugin. Version `4.9.0` being released after version `4.10.0` 🧐

Yeah this seems odd, not sure what happened. These github releases are created by lerna, not sure what happened here. But seems like the commit history shows the correct order.

**Comment by johnf** [comment]
> I saw you are importing both `@amplitude/analytics-react-native` and `@amplitude/analytics-browser`. Are these being used for the same project?

Sorry, that is a bit confusing.  `@amplitude/analytics-react-native` is in `dependencies` as it is being used in the app. `@amplitude/analytics-browser` is in devDependencies, I use it in a migration script I wrote to import my user creation times.

**Comment by kevinpagtakhan** [comment]
@johnf oh cool, no worries! I was just curious and totally open to any creative things other devs do 👍 We should have a new version for you shortly with the fix to this issue.
