### ISSUE TITLE
how do we use webAttributionPlugin? 

### ISSUE THREAD

**Issue by lynnshaoyu** [amplitude/Amplitude-TypeScript#259]
Hi, 

So it seems like the SDK changed without any alerts to users and our referral params are no longer being tracked.

The documentation here introduces a new "plugin" concept: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#web-attribution-enrichment-plugin

However I am unclear on how this should actually be used in the code. In the example in the documentation linked above, what is the "client"? Here is my attempt at using this new plugin but it is wrong because I have no idea where client is supposed to be coming from: https://github.com/Uniswap/interface/pull/5027

**Comment by kevinpagtakhan** [comment]
Hi @lynnshaoyu, thank you for choosing Amplitude! Web attribution should still be tracked without the use of plugin. This new change is backward compatible. We are introducing more plugins now and in the future to provide more features on top of the existing Amplitude SDK; but any existing features that didn't need a plugin should still be supported. Are you no longer seeing this tracked? Could be another issue if so.

**Comment by kevinpagtakhan** [comment]
@lynnshaoyu I also opened a pull request against our doc repo to show the code change suggestion I entered into your PR. This is helpful feedback to us. We appreciate you bringing up this topic to us.

**Comment by lynnshaoyu** [comment]
Hi Kevin, thank you for the documentation change and PR change suggestion! Appreciate the rapid clarification. 

I am confused about what you mean by "backwards compatible". 

I read the documentation [here](https://www.docs.developers.amplitude.com/data/sdks/marketing-analytics-browser/) which says "The Marketing Analytics Browser SDK extends the Browser SDK with automatic web attribution and page view tracking. This doc only includes the configuration related with web attribution and page view tracking. For other functionality check the [Browser SDK](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser)." 

My takeaway was: 
1) Using the Marketing Analytics Browser SDK automatically gives you web attribution and page view tracking. Therefore, Browser SDK (the original SDK) does not. 
2) We can use the web attribution _plugin_ to extend the Browser SDK to do what the Marketing Analytics Browser SDK does by default (aka add the referral params). 

Initially when our project first started using Amplitude, we had to set "includeReferrer" and "includeUtm" to be true manually, to ensure we got referral params. However the SDK then changed in a newer version to include these by default, hence we removed these params (see this PR: https://github.com/Uniswap/interface/pull/4358). 

Since then we have not seen web referral params that should be included by default (according to documentation) in our Amplitude project instance as a User property (which is the end use case our users expect). By referral params, I mean these web attribution params listed here: https://www.docs.developers.amplitude.com/data/sdks/marketing-analytics-browser/#web-attribution

**Comment by kevinpagtakhan** [comment]
> sing the Marketing Analytics Browser SDK automatically gives you web attribution and page view tracking. Therefore, Browser SDK (the original SDK) does not.

This is correct. Marketing Analytics Browser SDK is designed for an easy to setup SDK for our customers who have little to no dev resources. Browser SDK remains to be our primary SDK, and is more modular.

> We can use the web attribution plugin to extend the Browser SDK to do what the Marketing Analytics Browser SDK does by default (aka add the referral params).

This is also correct.

Our doc reflects the direction we are going towards. However, we understand that if we remove existing features from Browser SDK, then it will have to be a breaking change (version bump to 2.0), which we can do but decided to hold off. However to allow our customers to not experience interruptions, we kept the web attributions features as they are pre-plugin (plus some additional campaign params ie more click ids). The expectation is that customers who instrumented pre-plugin can keep the same configuration with no issues. Once we bump to 2.0 (no timeline yet), it will likely be removed and use of plugin will be required.

Now for the plugin, the plugin introduced additional (breaking) changes and that's why it's also optional to opt-in. We intend to add more features to the plugin in the future, and less likely to do so in the pre-plugin web attribution feature unless critical. Installing the plugin also disables the pre-plugin attribution feature to make sure only one attribution logic runs at a time.

It's unexpected that you are not seeing referral parameters without the plugin. I'm happy to help investigate this issue further. Do you have an app I can try to repro the issue?

**Comment by lynnshaoyu** [comment]
Hi Kevin, I see thanks for the explanation... we are not seeing both referral and utm parameters. Which we previously saw. 

Essentially we want to achieve feature parity with what "includeReferrer" and "includeUtm" would do in this SDK: https://www.docs.developers.amplitude.com/data/sdks/javascript/#web-attribution 

However we are not using that SDK, we are using the typescript-browser one. 

The documentation here ( https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#differences-from-base-sdk) explains that web-attribution plugin has some additional functionalities on top of what the base SDK does by default. 

My question is: is the web attribution plugin needed to achieve what "includeReferrer" and "includeUtm" does in the javascript SDK? 

Also would you be open to communicating via email instead? If so I can ask Uniswap's contact at Amplitude for your email.

**Comment by kevinpagtakhan** [comment]
Hi @lynnshaoyu,

The plugin should not be necessary to track referrer and UTM parameters. I believe we have [automated tests that assert this behavior](https://github.com/amplitude/Amplitude-TypeScript/blob/b8996d793f74d388c1a96e0cde5c0ac060c1e565/packages/analytics-browser-test/test/index.test.ts#L105-L223). I'd like to learn more and see how we can help you achieve the desired behavior may that be using the plugin or not. I'm happy to communicate via email.

**Comment by kevinpagtakhan** [comment]
Hi @lynnshaoyu,

I created this sample app to demo the attribution tracking without the attribution plugin:

Source code: https://github.com/kevinpagtakhan/ampg/blob/main/examples/attribution.html
Live: https://kevinpagtakhan.github.io/ampg/examples/attribution

On the live app, there are three sections:
1. Displays the how amplitude is initialized on the app.
2. A button to trigger an event. Each click should add an event to the event stream.
3. Displays an event stream containing the events sent by the app. This list should have the attribution event displayed first.

Try this link with fully populated campaign parameters: https://kevinpagtakhan.github.io/ampg/examples/attribution?utm_source=value_for_utm_source&utm_medium=value_for_utm_medium&utm_campaign=value_for_utm_campaign&utm_term=value_for_utm_term&utm_content=value_for_utm_content&referrer=value_for_referrer&referring_domain=value_for_referring_domain&dclid=value_for_dclid&gbraid=value_for_gbraid&gclid=value_for_gclid&fbclid=value_for_fbclid&ko_click_id=value_for_ko_click_id&msclkid=value_for_msclkid&ttclid=value_for_ttclid&twclid=value_for_twclid&wbraid=value_for_wbraid

Try this link with partially populated campaign parameters: https://kevinpagtakhan.github.io/ampg/examples/attribution?utm_source=value_for_utm_source&utm_medium=value_for_utm_medium&utm_campaign=value_for_utm_campaign&utm_term=value_for_utm_term&utm_content=value_for_utm_content&referrer=value_for_referrer&referring_domain=value_for_referring_domain

I hope this help in the meantime.
