### ISSUE TITLE
Don't force use of AsyncStorage for React Native

### ISSUE THREAD

**Issue by mmmoussa** [amplitude/Amplitude-TypeScript#266]
## Summary

In the React Native library, allow passing in a custom AsyncStorage library that is compatible with the AsyncStorage API.

## Motivations

In order to use this package in React Native we currently have to install `react-native-async-storage`. We don't currently use that library and would prefer to use `react-native-mmkv-storage` instead, which supports the same API interface as AsyncStorage. The reason for doing so is to achieve better performance.

You can even see an example of how this would be done here: https://github.com/Flagsmith/flagsmith-js-client/blob/main/lib/react-native-flagsmith/src/flagsmith-core.ts#L31

**Comment by mmmoussa** [comment]
Thanks @liuyang1520 for the guidance! I was confused by this in the README:

> In addition, this package relies on `@react-native-async-storage/async-storage`, which must also be installed

**Comment by nuramirahs** [comment]
Hi @liuyang1520,

I'm currently facing the same issue as well. Even after setting up our own custom storage provider, we're still running into the error: `Error: [@RNC/AsyncStorage]: NativeModule: AsyncStorage is null`

Eager to know if there's a way we can fully remove the dependency on `@react-native-async-storage/async-storage` from the Amplitude package or if there's a recommended workaround for this issue.

Some guidance would be greatly appreciated, thanks!

**Comment by sumersao** [comment]
Has anyone solved these problems?
