### ISSUE TITLE
Flushing events not working in @amplitude/analytics-node

### ISSUE THREAD

**Issue by hanna-becker** [amplitude/Amplitude-TypeScript#271]
Hello there! I am using @amplitude/analytics-node in a lambda function on AWS, so instead of flushing events automatically in an interval, I would like to flush them at the end of the lambda callback. The documentation on flushing is very brief, unfortunately, and I could not get it working. Then again, I don't know if there's a misunderstanding on my side. This is what I tried:

```
await amplitude.init(AMPLITUDE_API_KEY, { logLevel: amplitude.Types.LogLevel.Debug }).promise;
await amplitude.track('Backend signUp confirmed', undefined, { user_id: userId }).promise;
await amplitude.flush();
```

The problem here is that awaiting the "track" call takes 10 seconds (the default flushInterval), which is too slow for my purposes. Also the event shows up 4 times  in the Analytics console for some reason.

So I tried the same without awaiting the track call like so (hoping that this would only queue the event):

```
await amplitude.init(AMPLITUDE_API_KEY, { logLevel: amplitude.Types.LogLevel.Debug }).promise;
amplitude.track('Backend signUp confirmed', undefined, { user_id: userId });
await amplitude.flush();
```
However, in this case, the event does not show up in the Analytics console at all. 

I suppose a workaround would be to just set a very low flushInterval when initializing amplitude and not flush manually. Still, I'd prefer having control of the flushing myself.

**Comment by kevinpagtakhan** [comment]
Hi @hanna-becker thank you for choosing Amplitude! I think what you'll want here is to not await on track, then await on flush, but with the `.promise` interface. So something like:

```ts
await amplitude.init(AMPLITUDE_API_KEY, { logLevel: amplitude.Types.LogLevel.Debug }).promise;
amplitude.track('Backend signUp confirmed', undefined, { user_id: userId });
await amplitude.flush().promise;
```

**Comment by hanna-becker** [comment]
Oh, my bad, I missed converting the callback into a promise on the last call. Now it works. Thank you!
In any case, I think it may be worth mentioning in the docs in the flushing section that the track method when not awaited adds events to the queue. I really wasn't sure it would do that and thought there may be a different method to look for.

**Comment by kevinpagtakhan** [comment]
That's a great suggestion! I will communicate this pain point with the rest of the team and we will add more info about tracking and flushing.
