### ISSUE TITLE
Identify not working in "@amplitude/analytics-node"

### ISSUE THREAD

**Issue by hanna-becker** [amplitude/Amplitude-TypeScript#274]
I am trying to add user properties after initializing amplitude and before sending an event in a lambda function on AWS.

Without the identify part, the event gets sent and I can see it in the Amplitude console:
```
  await amplitude.init(AMPLITUDE_API_KEY, { logLevel: amplitude.Types.LogLevel.Debug }).promise;
  amplitude.track('some event', undefined, { user_id: userId });
  await amplitude.flush().promise;
```

Adding properties via identify like so, and the event does not make it to the console any longer:

```
  await amplitude.init(AMPLITUDE_API_KEY, { logLevel: amplitude.Types.LogLevel.Debug }).promise;
  
  // adding this part
  const identifyObj = new amplitude.Identify();
  identifyObj.set('email', email);
  identifyObj.set('env', process.env.ENV);
  amplitude.identify(identifyObj);

  amplitude.track('some event', undefined, { user_id: userId });
  await amplitude.flush().promise;
```
I also see this not very helpful log statement in the lambda logs: `ERROR Amplitude Logger [Error]: invalid`.

## Expected Behavior
The event should be visible in the Amplitude console, along with the user properties 'email' and 'env'.

## Current Behavior
The event does not get sent.

## Steps to Reproduce
See code above.

## Environment
- JS SDK Version: 0.6.0
- Installation Method: yarn
- Browser and Version: node 14

**Comment by liuyang1520** [comment]
Hi @hanna-becker , thanks for supporting us!

Could you please try:
```js
amplitude.identify(identifyObj, { user_id: userId });
```

This works in my local. If this works for you too, then we will update the log and docs for this.

Thanks!

**Comment by hanna-becker** [comment]
Yes, this works. Thank you!
