### ISSUE TITLE
@amplitude/analytics-browser triggers the loading of @types/node which affects the signature of setTimeout

### ISSUE THREAD

**Issue by stof** [amplitude/Amplitude-TypeScript#281]
## Expected Behavior

Importing `@amplitude/analytics-browser` should not force the loading of types defined in `@types/node`

## Current Behavior

`@amplitude/analytics-browser` imports `@amplitude/analytics-core`, which references the node types:

```
node_modules/@types/node/index.d.ts
  Type library referenced via 'node' from file 'node_modules/@amplitude/analytics-core/lib/esm/plugins/destination.d.ts' with packageId '@types/node/index.d.ts@18.11.9'


The beginning of `node_modules/@amplitude/analytics-core/lib/esm/plugins/destination.d.ts` looks like that:

```ts
/// <reference types="node" />
import { Config, DestinationContext as Context, DestinationPlugin, Event, InvalidResponse, PayloadTooLargeResponse, PluginType, RateLimitResponse, Response, Result, SuccessResponse } from '@amplitude/analytics-types';
```

This reference to the node types causes the loading of all of `@types/node`, which will then define the return type of `setTimeout` as being a `Timeout` object and not a number, which is very annoying when writing a project targetting the web.

## Possible Solution

`@amplitude/analytics-core` should not reference node types.

And ideally, a CI job should ensure that `@amplitude/analytics-browser` stays free from references to `@types/node` as that's not the first time a similar issue happens (see #200)

## Steps to Reproduce
1. `yarn add --dev @amplitude/analytics-browser @types/node`
2. Add this code in `test.ts`: 
    ```ts
    import * as amplitude from '@amplitude/analytics-browser'

    const a: number = setTimeout(function () {})
    ```
3. Add this code in `tsconfig.json`:
    ```json
    {
        "compilerOptions": {
            "noEmit": true,
            "esModuleInterop": true,
            "lib": ["dom"],
            "strict": true,
            "types": []
        },
        "files": [
            "test.ts"
        ]
    }

    ```
4. Run the typescript type checker on that code (`tsc -p .`)
5. See the error `Type 'Timeout' is not assignable to type 'number'.` reported on the `a` variable assignment
6. Comment the import of Amplitude and see the error disappear.

## Environment
- JS SDK Version: `@amplitude/analytics-browser` 1.6.2
- Installation Method: yarn
- Browser and Version: n/a

**Comment by hatem-72** [comment]
This also breaks integration with my typed React-Native project. Patched for now.

**Comment by stof** [comment]
Marking the [`scheduled` property of the Destination plugin](https://github.com/amplitude/Amplitude-TypeScript/blob/c3b5d2ddf9439089b1eb1020e0ee87a64fb974d8/packages/analytics-core/src/plugins/destination.ts#L38) as private might fix this as private fields don't define their type in declaration files (the compiler won't care about them as accessing them is an error anyway).
AFAICT, this `scheduled` field is not meant to be accessed externally (otherwise, changing it from a boolean to a number or Timeout object would have been a BC break between `@amplitude/analytics-core` 0.10.0 and 0.10.1)

**Comment by kevinpagtakhan** [comment]
Hey @stof we just merged the fix and release it. Should be available in the latest version. We'll improve our builds to catch this in CI. Thank you so much.
