### ISSUE TITLE
[Privacy] Add a storage option

### ISSUE THREAD

**Issue by Nikitina-Ann** [amplitude/Amplitude-TypeScript#286]
Hello!
We need to use Amplitude without using cookies or local storage.

Now we use the **disableCookies** option, but Amplitude-TypeScript doesn't have the same option to disable localStorage.
I found an issue for Amplitude-JavaScript about this topic and the pull request https://github.com/amplitude/Amplitude-JavaScript/pull/320 to add a new option: **storage**. Will Amplitude-TypeScript have a **storage** option or option to disable localStorage?

**Comment by kevinpagtakhan** [comment]
Hi @Nikitina-Ann, thank you for choosing Amplitude. This configuration is available. Here's an example code to configure the Amplitude SDK to not use cookies or local storage:

``
import { createInstance } from '@amplitude/analytics-browser';
import { MemoryStorage } from '@amplitude/analytics-core';

const amplitude = createInstance();
amplitude.init('API_KEY', 'USER_ID', {
  cookieStorage: new MemoryStorage(),
  storageProvider: new MemoryStorage(),
})
```

I hope this is helpful. Additionally, if you want to check the different storage options one may use, I added some tests to document the different storage options/scenarios here: https://github.com/amplitude/Amplitude-TypeScript/pull/294/files.

**Comment by kevinpagtakhan** [comment]
@Nikitina-Ann I see what you mean here. I'm reopening this issue. I can confirm that the SDK does not allow opting out of cookie storage and local storage. We'll have to make some code changes to allow this to happen. One thing I will call out is, using a non persistent storage for web attribution feature will disable `trackNewCampaigns` option.

**Comment by kevinpagtakhan** [comment]
Hi @Nikitina-Ann, I'm trying to get back to my team and make sure we provide the appropriate solution for you. Meanwhile, wanted to take this chance to ask if anything has changed since we last been in contact? Would love to incorporate if you have change with how you want to use Amplitude SDK with regards to storage.
