### ISSUE TITLE
Unable to create an event in Reac Native App - Getting API Error

### ISSUE THREAD

**Issue by AlexTeixeira** [amplitude/Amplitude-TypeScript#292]
## Expected Behavior

Method track event should send an event to the console every time is called in react native project

## Current Behavior

It's work 3 times and now I get this error :

`Amplitude Logger [Error]: Invalid API key: `

## Steps to Reproduce

```
export const initAmplitude = async (userEmail: string) => {

  try {
    amplitude.init("OUR_API_KEY", "someEmail@email.com", {
      serverZone: amplitude.Types.ServerZone.EU,
    })
    trackEvent("App Opened 2", { userEmail })
  } catch (error) {
    console.error(error)
  }

}

export const trackEvent = (eventName: string, eventProperties: Record<string, any> | undefined = undefined) => {
  amplitude.logEvent(eventName, eventProperties)
}

```

## Environment
- JS SDK Version: 0.7.0 
- Installation Method: yarn
- Browser and Version: React Native version 0.67.2 with react 18.2.0

**Comment by kevinpagtakhan** [comment]
@AlexTeixeira thank you for choosing amplitude! For the API key you are using, is this for a project created on Amplitude EU (https://analytics.eu.amplitude.com)?

**Comment by AlexTeixeira** [comment]
@kevinpagtakhan Hi, thanks for the quick answer. It's look like that the problem come from the ServerZone parameter. I'm not the manager or the amplitude account and I set this ServerZone because we are in EU ^^'.

Thanks :)
