### ISSUE TITLE
The Types are not exported properly

### ISSUE THREAD

**Issue by hegdemohan** [amplitude/Amplitude-TypeScript#295]
## Expected Behavior
The types from Amplitude browser sdk are exported properly

## Current Behavior
In the track function, the definition is as follows, 
```
track(eventInput: string | BaseEvent, eventProperties?: Record<string, any> | undefined, eventOptions?: EventOptions | undefined): AmplitudeReturn<Result>
```

So based on that if we want to write a wrapper function as shown below, 
```
function trackEvent(
    type: string,
    properties?: Record<string, any>
  ): AmplitudeReturn<Result> {
    return track(type, properties);
  }
```
it is not possible to import the types `AmplitudeReturn` and `Result`.

We get an error that `Module '"@amplitude/analytics-browser"' has no exported member 'AmplitudeReturn'.` and same for `Result` type.

## Environment
"@amplitude/analytics-browser": "1.6.6"
Link to codesandbox  -> https://codesandbox.io/s/withered-tree-dht7y7?file=/src/App.tsx

**Comment by kevinpagtakhan** [comment]
Hi @hegdemohan, thank you for choosing Amplitude. You can export all type definition as the following:

```ts
import { track, Types } from '@amplitude/analytics-browser';

function trackEvent(
  type: string,
  properties?: Record<string, any>
): Types.AmplitudeReturn<Types.Result> {
  return track(type, properties);
}

You can also use this API doc: https://amplitude.github.io/Amplitude-TypeScript/modules/_amplitude_analytics_browser.html as reference for @amplitude/analytics-browser.
