### ISSUE TITLE
No option to `includeUtm`

### ISSUE THREAD

**Issue by AshRing** [amplitude/Amplitude-TypeScript#296]
## Expected Behavior

Ability to set `includeUtm` config option when initializing amplitude.

## Current Behavior

There is not an option to set `includeUtm` and setting it in what I assume to be the right spot in the init config throws a TypeError. The [documentation](https://www.docs.developers.amplitude.com/data/sdks/javascript/#track-utm-parameters) mentions it as a part of the legacy javascript SDK. I looked through all the types in the package and was not able to find `includeUtm`. Was this removed or renamed? How can we include UTM tracking with the newer SDK?

![image](https://user-images.githubusercontent.com/20742827/207149061-5fbbd555-63b5-476c-8fb8-2c73520dcca3.png)

## Steps to Reproduce

1. Install amplitude CLI
2. Ampli pull
3. initialize ampli and try to add `includeUtm` property to the client configuration
4. See typeerror

## Environment
- JS SDK Version: We are using the amplitude CLI along with `"@amplitude/analytics-browser": "^1.6.1",`. 
- Installation Method: yarn to install @amplitude/analytics-browser and amplitude CLI to pull down and track typed events
- Browser and Version: Chrome Version 108.0.5359.98

**Comment by jalagar** [comment]
@AshRing is there a reason you closed the issue? Did you figure out how this worked?

**Comment by yuhao900914** [comment]
Hi @jalagar, 
In the latest browser SDK you don’t need to manually include the UTM any more. Enable web attribution tracking include track all UTM parameters, referrer related stuff and clickIds.

https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#web-attribution

https://www.docs.developers.amplitude.com/data/sdks/marketing-analytics-browser/#web-attribution
