### ISSUE TITLE
Some unknown User Properties appeared when I migrated amplitude-js to @amplitude/analytics-browser

### ISSUE THREAD

**Issue by richard-li-next** [amplitude/Amplitude-TypeScript#297]
## Summary

Some unknown User Properties appeared when I migrated amplitude-js to @amplitude/analytics-browser

```
import { init, Identify, identify as amplitudeIdentify } from '@amplitude/analytics-browser'

const setUserProperties = (
  properties: Record<string, any>
): void => {
  const identify = new Identify()
  Object.entries(properties).forEach(([key, value]) => {
    identify.set(key, value)
  })
  amplitudeIdentify(identify)
}

init('key', '', { appVersion })
setUserProperties({ 
  'User Name': '',
  // ...
})
```

<img width="385" alt="image" src="https://user-images.githubusercontent.com/65935211/207281005-3726e151-982f-4a20-bd99-bcca1b2551bb.png">

**Comment by yuhao900914** [comment]
Hi @richard-li-next, thanks for choosing amplitude.  
That parameter is related to marketing analytics. If you are interested in, please step [here](https://www.docs.developers.amplitude.com/data/sdks/marketing-analytics-browser/#first-touch-attribution) to check it out.
If you don't want to track your web attribution. You can also disable that by the following code. 
```
amplitude.init(API_KEY, OPTIONAL_USER_ID, {
  attribution: {
     disable: false
  },
});
```
