### ISSUE TITLE
onExitPage option missing for amplitude init function

### ISSUE THREAD

**Issue by abhi-gn** [amplitude/Amplitude-TypeScript#313]
onExitPage option, that is there in the [js sdk](https://developers.amplitude.com/docs/advanced-settings#using-sendbeacon-only-when-exiting-page), is missing in the amplitude init function

## Expected Behavior
Expected to find `onExitPage` option. Or some documentation in case it is removed or replaced by something else.

## Current Behavior
 `onExitPage` option is not present in the init function

## Steps to Reproduce
1. Install the Typescript SDK
2. Try to `init` Amplitude sdk

## Environment
- TS SDK Version: analytics-browser@1.6.8
- Installation Method: yarn
- Browser and Version: Chrome/VSCode

**Comment by kevinpagtakhan** [comment]
Hi @abhi-gn, we have migration docs posted here: https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#flush-or-onexitpage The link anchors on this specific topic. Let me know if this helps!

**Comment by abhi-gn** [comment]
Thanks @kevinpagtakhan, this helps.
