### ISSUE TITLE
Figuring out why `Amplitude Logger` warns about overriding web attribution behaviour when web attribution browser plugin is used

### ISSUE THREAD

**Issue by ahmedmaazin** [amplitude/Amplitude-TypeScript#314]
## Summary
I am using https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#web-attribution-enrichment-plugin in our setup. 

_Versions:_
**@amplitude/analytics-browser: ^1.6.8**
**@amplitude/plugin-web-attribution-browser: ^0.5.4**

I need help figuring out why the following warning getting reported. We have no web attribution behaviour defined prior to this plugin.

`Amplitude Logger [Warn]: @amplitude/plugin-web-attribution-browser overrides web attribution behavior defined in @amplitude/analytics-browser`

Should I simply disable the default attribution options from the browser SDK when the plugin is being used, like:
```javascript
...
attribution: {
    disabled: true,
},
```
Question is, will the attribution work if so?

**Comment by kevinpagtakhan** [comment]
Hi @ahmedmaazin, a simpler version of web attribution is built in to `@amplitude/analytics-browser` and is enabled by default. The `@amplitude/plugin-web-attribution-browser` package has more web attribution features but was created as a separate plugin. The warning just states that if you are installing and adding the plugin `@amplitude/plugin-web-attribution-browser`, it disables the simpler version of web attribution that's built in to `@amplitude/analytics-browser` to ensure only web attribution is only tracked by one component.

**Comment by ahmedmaazin** [comment]
@kevinpagtakhan Thanks for the swift response. I can understand now that the warning itself isn't an issue. 

However, I'm thinking about ways to clear that warning. If I add the attribution {disabled: true} option to the built-in one, would that be sufficient enough to get rid of the warning and still get the attribution working at the same time with the plugin?

The reason behind using this plugin is simply that we don't want to use the marketing analytics browser SDK and still use the `resetSessionOnNewCampaign` option for attribution.

**Comment by kevinpagtakhan** [comment]
Yes, you should be able suppress the warning by setting attribution config to `false` when calling the `init` function, just as you stated above. Here's our code reference if you are curious to see: https://github.com/amplitude/Amplitude-TypeScript/blob/f5d90dc91532f94b514c55fee306c24f441fc95c/packages/plugin-web-attribution-browser/src/web-attribution.ts#L21-L24

**Comment by ahmedmaazin** [comment]
@kevinpagtakhan Great! Indeed I was curious, thanks for sharing.
