### ISSUE TITLE
Cookie Consent

### ISSUE THREAD

**Issue by Liroo** [amplitude/Amplitude-TypeScript#327]
## Summary

Hey, I recently updated our SDK to that one. I am implementing a cookie consent banner and I wanted to ask some questions:

- Are cookies mandatory for amplitude analytics / experiments to work well?
- For such a feature (cookie consent banner). I would have init amplitude with `disableCookies: true` then re-init amplitude when the user would have accept the cookies. Is this the way to go with amplitude, is there any method to re-enable them on the fly?

Thanks!

**Comment by yuhao900914** [comment]
Hi @Liroo 
- Cookies are not mandatory for amplitude analytics. If cookies are disabled, SDK will use local storage instead. 
- For Amplitude browser SDK, we provide defer initialization. You can call tack before initialization. And call the init method after the customer grants cookie consent. The track events will be sent to the server after you call the init method.
