### ISSUE TITLE
Can't resolve 'http' and 'https' in analytics-node/lib/esm/transports

### ISSUE THREAD

**Issue by shunyun-bp** [amplitude/Amplitude-TypeScript#340]
## Expected Behavior
First try of the Node library, following instructions at 

## Current Behavior
Imported @amplitude/analytics-node into project. Added the import and init code. NPM start and get error.

## Steps to Reproduce
1. > npm install @amplitude/analytics-node
2. Pasted `
import { init } from '@amplitude/analytics-node';
init('123456asdfasdfas');
` 
into index.js 
3. npm start

## Environment
package.json includes:
` "dependencies": {
    "@amplitude/analytics-node": "^1.1.0",
    "@apollo/client": "^3.5.5",
    "@emotion/react": "^11.6.0",
    "@emotion/styled": "^11.6.0",
    "@hot-loader/react-dom": "^17.0.2",
    "@mui/icons-material": "^5.1.1",
    "@mui/material": "^5.1.1",
    "apollo-link": "^1.2.14",
    "apollo-link-http": "^1.5.17",
    "apollo3-cache-persist": "^0.13.0",
    "aws-appsync-auth-link": "^3.0.7",
    "aws-appsync-subscription-link": "^3.0.9",
    "buffer": "^6.0.3",
    "graphql": "^15.8.0",
    "is-json": "^2.0.1",
    "is-object": "^1.0.2",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "react-hot-loader": "^4.13.0",
    "reactjs-heap": "^1.0.3"
  },
  "devDependencies": {
    "@babel/core": "^7.15.8",
    "@babel/plugin-proposal-class-properties": "^7.14.5",
    "@babel/preset-env": "^7.15.8",
    "@babel/preset-react": "^7.14.5",
    "@types/chrome": "^0.0.161",
    "@types/react": "^17.0.33",
    "@types/react-dom": "^17.0.10",
    "archiver": "^5.3.0",
    "babel-eslint": "^10.1.0",
    "babel-loader": "^8.2.2",
    "babel-preset-react-app": "^10.0.0",
    "copy-webpack-plugin": "^7.0.0",
    "css-loader": "^6.5.0",
    "eslint": "^8.27.0",
    "eslint-config-react-app": "^7.0.1",
    "eslint-plugin-flowtype": "^8.0.3",
    "eslint-plugin-import": "^2.25.2",
    "eslint-plugin-jsx-a11y": "^6.4.1",
    "eslint-plugin-react": "^7.26.1",
    "eslint-plugin-react-hooks": "^4.2.0",
    "file-loader": "^6.2.0",
    "fs-extra": "^10.0.0",
    "html-loader": "^3.0.0",
    "html-webpack-plugin": "^5.5.0",
    "prettier": "^2.4.1",
    "sass": "^1.58.1",
    "sass-loader": "^12.2.0",
    "source-map-loader": "^3.0.0",
    "style-loader": "^3.3.1",
    "terser-webpack-plugin": "^5.2.4",
    "ts-loader": "^9.2.6",
    "typescript": "^4.4.4",
    "webpack": "^5.60.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.3.1"
  }`

Output:
`ERROR in ./node_modules/@amplitude/analytics-node/lib/esm/transports/http.js 3:0-29
Module not found: Error: Can't resolve 'http' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports'
Did you mean './http'?
Requests that should resolve in the current directory need to start with './'.
Requests that start with a name are treated as module requests and resolve within module directories (node_modules).
If changing the source code is not an option there is also a resolve options called 'preferRelative' which tries to resolve these kind of requests in the current directory too.

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "http": require.resolve("stream-http") }'
        - install 'stream-http'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "http": false }
resolve 'http' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports'
  Parsed request is a module
  using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/package.json (relative path: ./lib/esm/transports)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules
        single file module
          using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/package.json (relative path: ./node_modules/http)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.jpg doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.jpeg doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.png doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.gif doesn't exist
            .eot
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.eot doesn't exist
            .otf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.otf doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.svg doesn't exist
            .ttf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.ttf doesn't exist
            .woff
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.woff doesn't exist
            .woff2
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.woff2 doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.tsx doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http.css doesn't exist
        /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/http doesn't exist
      /Users/sonion@bigpanda.io/code/Projects/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@amplitude/analytics-node/lib/esm/config.js 3:0-41 7:76-80
 @ ./node_modules/@amplitude/analytics-node/lib/esm/node-client.js 4:0-41 25:38-51
 @ ./node_modules/@amplitude/analytics-node/lib/esm/index.js 2:0-35 3:0-47 3:0-47 4:17-27 4:45-65 4:78-93 4:102-113 4:126-141 4:152-165 4:177-191 4:204-219 4:233-249 4:259-271 4:281-293
 @ ./src/pages/Popup/Popup.jsx 25:0-49 26:0-4
 @ ./src/pages/Popup/index.jsx 23:0-28 154:36-41

ERROR in ./node_modules/@amplitude/analytics-node/lib/esm/transports/http.js 4:0-31
Module not found: Error: Can't resolve 'https' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
        - add a fallback 'resolve.fallback: { "https": require.resolve("https-browserify") }'
        - install 'https-browserify'
If you don't want to include a polyfill, you can use an empty module like this:
        resolve.fallback: { "https": false }
resolve 'https' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports'
  Parsed request is a module
  using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/package.json (relative path: ./lib/esm/transports)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/transports/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/esm/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/lib/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/analytics-node/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/@amplitude/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules
        single file module
          using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/package.json (relative path: ./node_modules/https)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.jpg doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.jpeg doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.png doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.gif doesn't exist
            .eot
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.eot doesn't exist
            .otf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.otf doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.svg doesn't exist
            .ttf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.ttf doesn't exist
            .woff
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.woff doesn't exist
            .woff2
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.woff2 doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.tsx doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https.css doesn't exist
        /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/https doesn't exist
      /Users/sonion@bigpanda.io/code/Projects/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/@amplitude/analytics-node/lib/esm/config.js 3:0-41 7:76-80
 @ ./node_modules/@amplitude/analytics-node/lib/esm/node-client.js 4:0-41 25:38-51
 @ ./node_modules/@amplitude/analytics-node/lib/esm/index.js 2:0-35 3:0-47 3:0-47 4:17-27 4:45-65 4:78-93 4:102-113 4:126-141 4:152-165 4:177-191 4:204-219 4:233-249 4:259-271 4:281-293
 @ ./src/pages/Popup/Popup.jsx 25:0-49 26:0-4
 @ ./src/pages/Popup/index.jsx 23:0-28 154:36-41`

**Comment by kevinpagtakhan** [comment]
Hi @shunyun-bp! Thank you for choosing Amplitude! Are you planning to use Amplitude in a client-side (browser) project, but developing your project using Node.js?

**Comment by shunyun-bp** [comment]
Hi Kevin.  This is for a Chrome extension.  Amplitude seems to be the only valid solution for an extension, as other analytics platforms require injection, which isn't allowed in Chrome Extensions manifest v3.  So I'm going to run the Amplitude code in the background script. I use the popup and messages; user takes an action, popup sends to background script, background execute async actions.  This way I'm not exposing myself to potential screen-scraping of other extensions.

BTW, I'm chasing down the webpack backfill path on this...

**Comment by shunyun-bp** [comment]
Added to webpack.config:
`fallback: {
      "https": require.resolve("https-browserify"),
      "http": require.resolve("stream-http")
    },`
and installed those packages.

Now getting:
`ERROR in ./node_modules/aws-appsync-subscription-link/lib/realtime-subscription-handshake-link.js 72:13-28
Module not found: Error: Can't resolve 'uuid' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/lib'
resolve 'uuid' in '/Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/lib'
  Parsed request is a module
  using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/package.json (relative path: ./lib)
    Field 'browser' doesn't contain a valid alias configuration
    resolve as module
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/lib/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules
        single file module
          using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/package.json (relative path: ./node_modules/uuid)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.jpg doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.jpeg doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.png doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.gif doesn't exist
            .eot
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.eot doesn't exist
            .otf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.otf doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.svg doesn't exist
            .ttf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.ttf doesn't exist
            .woff
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.woff doesn't exist
            .woff2
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.woff2 doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.tsx doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid.css doesn't exist
        /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/aws-appsync-subscription-link/node_modules/uuid doesn't exist
      /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/node_modules doesn't exist or is not a directory
      looking for modules in /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules
        single file module
          using description file: /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/package.json (relative path: ./node_modules/uuid)
            no extension
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid doesn't exist
            .jpg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.jpg doesn't exist
            .jpeg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.jpeg doesn't exist
            .png
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.png doesn't exist
            .gif
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.gif doesn't exist
            .eot
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.eot doesn't exist
            .otf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.otf doesn't exist
            .svg
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.svg doesn't exist
            .ttf
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.ttf doesn't exist
            .woff
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.woff doesn't exist
            .woff2
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.woff2 doesn't exist
            .js
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.js doesn't exist
            .jsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.jsx doesn't exist
            .ts
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.ts doesn't exist
            .tsx
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.tsx doesn't exist
            .css
              Field 'browser' doesn't contain a valid alias configuration
              /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid.css doesn't exist
        /Users/sonion@bigpanda.io/code/Projects/demosim-cloud-extension/node_modules/uuid doesn't exist
      /Users/sonion@bigpanda.io/code/Projects/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/code/node_modules doesn't exist or is not a directory
      /Users/sonion@bigpanda.io/node_modules doesn't exist or is not a directory
      /Users/node_modules doesn't exist or is not a directory
      /node_modules doesn't exist or is not a directory
 @ ./node_modules/aws-appsync-subscription-link/lib/index.js 20:45-94
 @ ./src/pages/Popup/index.jsx 27:0-80 100:4-35
`

**Comment by kevinpagtakhan** [comment]
@shunyun-bp, for browser extension projects, we recommend using `@amplitude/analytics-browser` package

**Comment by shunyun-bp** [comment]
Using @amplitude/analytics-browser solved the issue.
