### ISSUE TITLE
export 'SessionManager' (imported as 'SessionManager') was not found in '@amplitude/analytics-client-common'

### ISSUE THREAD

**Issue by eavalosrextie** [amplitude/Amplitude-TypeScript#348]
angular "ng serve" shows me:

./node_modules/@amplitude/analytics-browser/lib/esm/config.js:27:28-42 - Error: export 'SessionManager' (imported as 'SessionManager') was not found in '@amplitude/analytics-client-common' (possible exports: BASE_CAMPAIGN, CampaignParser, CampaignTracker, CookieStorage, FetchTransport, IdentityEventSender, getAnalyticsConnector, getCookieName, getGlobalScope, getLanguage, getOldCookieName, getQueryParams)

./node_modules/@amplitude/analytics-browser/lib/esm/config.js:140:41-55 - Error: export 'SessionManager' (imported as 'SessionManager') was not found in '@amplitude/analytics-client-common' (possible exports: BASE_CAMPAIGN, CampaignParser, CampaignTracker, CookieStorage, FetchTransport, IdentityEventSender, getAnalyticsConnector, getCookieName, getGlobalScope, getLanguage, getOldCookieName, getQueryParams)

But I need to understand why? any suggestions ?

my dependencies are:

{ "name": "webapp-final", "version": "1.0.0", "scripts": { "ng": "ng", "start": "ng serve", "build": "ng build --configuration production", "watch": "ng build --watch --configuration development", "test": "ng test", "prepare": "husky install", "format": "prettier --write \"./src/**/*.{ts,css,scss,html}\"", "lint": "ng lint" }, "private": true, "dependencies": { "@abacritt/angularx-social-login": "1.1.0", "@amplitude/analytics-browser": "1.7.0", "@angular/animations": "13.3.12", "@angular/cdk": "13.3.9", "@angular/common": "13.3.12", "@angular/compiler": "13.3.12", "@angular/core": "13.3.12", "@angular/flex-layout": "13.0.0-beta.38", "@angular/forms": "13.3.12", "@angular/material": "13.3.9", "@angular/platform-browser": "13.3.12", "@angular/platform-browser-dynamic": "13.3.12", "@angular/router": "13.3.12", "@ionic/storage-angular": "3.0.6", "@rextie/wc-rextie-auth-forms": "0.0.23", "@sentry/angular": "7.34.0", "@sentry/tracing": "7.34.0", "@types/swiper": "5.4.0", "chart.js": "2.9.4", "chartjs-plugin-datalabels": "0.7.0", "chartjs-plugin-labels": "1.1.0", "cropperjs": "1.5.6", "date-fns": "2.16.1", "fast-xml-parser": "3.21.1", "google-libphonenumber": "3.2.31", "intl-tel-input": "17.0.19", "ng-recaptcha": "9.0.0", "ng2-charts": "2.4.2", "ng2-tel-input": "2.3.0", "ngx-clipboard": "13.0.1", "ngx-cookie-service": "13.2.1", "ngx-countdown": "13.0.0", "ngx-daterangepicker-material": "4.0.0", "ngx-dropzone": "3.1.0", "ngx-mask": "11.1.5", "ngx-spinner": "13.1.1", "ngx-useful-swiper": "9.0.3", "rxjs": "6.6.2", "rxjs-observe": "2.1.5", "swiper": "5.4.5", "tslib": "2.3.0", "zone.js": "0.11.4" }, "devDependencies": { "@angular-devkit/build-angular": "13.3.10", "@angular-eslint/builder": "13.5.0", "@angular-eslint/eslint-plugin": "13.5.0", "@angular-eslint/eslint-plugin-template": "13.5.0", "@angular-eslint/schematics": "13.5.0", "@angular-eslint/template-parser": "13.5.0", "@angular/cli": "13.3.10", "@angular/compiler-cli": "13.3.12", "@types/jasmine": "3.10.0", "@types/node": "12.11.1", "@typescript-eslint/eslint-plugin": "5.27.1", "@typescript-eslint/parser": "5.27.1", "eslint": "8.17.0", "eslint-plugin-security": "^1.6.0", "husky": "8.0.0", "jasmine-core": "4.0.0", "karma": "6.3.0", "karma-chrome-launcher": "3.1.0", "karma-coverage": "2.1.0", "karma-jasmine": "4.0.0", "karma-jasmine-html-reporter": "1.7.0", "lint-staged": "13.1.0", "prettier": "2.8.2", "typescript": "4.6.2" } } 

$ node -v && npm -v
v16.18.0
8.19.2

**Comment by kevinpagtakhan** [comment]
Hi @eavalosrextie! It must be due to a change we introduced in our internal packages. Any chance you can upgrade to the latest version? It should solve this issue
