### ISSUE TITLE
Passing a non-email user_id field could give a clearer error.

### ISSUE THREAD

**Issue by andrewfrankcare** [amplitude/Amplitude-TypeScript#350]
## Expected Behavior

The following code should work:

```
  track('Button Clicked 2', undefined, {
            user_id: 'Anonymous',
        });
```

## Current Behavior

It appears that passing a `user_id` that is not an email address causes an error. I get this in my logs:

```
Amplitude Logger [Error]: Event rejected due to exceeded retry count
Amplitude Logger [Debug]: {
  "type": "invoke public method",
  "name": "track",
  "args": [
    "Button Clicked 2",
    null,
    {
      "user_id": "Anonymous"
    }
  ],
  "stacktrace": [
    "at Analytics.trackMessageInference (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/.common/analytics.js:33:36)",
    "at Object.run (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/runSlackMessageInference.js:107:19)",
    "at processTicksAndRejections (node:internal/process/task_queues:96:5)",
    "at async handleSQSEvent (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/app.js:51:13)",
    "at async poll (/Users/aleppard/frank/one/Frank_Slack/queue_consumer/dist/poll.js:47:9)"
  ],
  "time": {
    "start": "2023-03-22T22:58:06.136Z",
    "end": "2023-03-22T23:00:15.903Z"
  },
  "states": {
    "before": {
      "config.apiKey": "b8e03107dbf9088cf67165fca4ae0eab",
      "timeline.queue.length": 0
    },
    "after": {
      "config.apiKey": "b8e03107dbf9088cf67165fca4ae0eab",
      "timeline.queue.length": 0
    }
  }
}
```

This threw me as I didn't realise the problem it was having was the `user_id`. Changing the `user_id` to `'user@amplitude.com` works for me. 

## Possible Solution

Obviously for me I can just pass an email looking field which will fix the problem.

## Steps to Reproduce

As documented above.

## Environment

- Node 16
- "@amplitude/analytics-node": "^1.1.0",
- Yarn

**Comment by Mercy811** [comment]
Hi @andrewfrankcare, thanks for using Amplitude. 

"Anonymous" is a reserved/invalid keyword. Amplitude TS Node SDK uses HTTP V2 API. You can refer [HTTP V2 doc](https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/?h=htt#device-ids-and-user-ids-minimum-length) for more requirements of user Id and device Id
