### ISSUE TITLE
Unexpected keyword 'this'

### ISSUE THREAD

**Issue by larkonesvk** [amplitude/Amplitude-TypeScript#355]
The app crashes after startup.
## Expected Behavior

Not crash.
## Current Behavior

`error: SyntaxError: /node_modules/@amplitude/analytics-react-native/src/react-native-client.ts: Unexpected keyword 'this'. (115:46)`
## Steps to Reproduce

Install latest version.
```
yarn add @amplitude/analytics-react-native
yarn add @react-native-async-storage/async-storage
```
<img width="380" alt="Screenshot 2023-03-28 at 16 27 21" src="https://user-images.githubusercontent.com/20130702/228270828-ba9aca51-3340-4829-bc16-21b756bd389b.png">

## Environment
```
 "@amplitude/analytics-react-native": "^1.1.1",
 "react-native": "^0.68.2",
```

**Comment by Mercy811** [comment]
Hi @larkonesvk, I cannot reproduce it. Here is an [example react native project](https://github.com/amplitude/Amplitude-TypeScript/tree/v1.x/examples/react-native/app). Hope this is helpful to get you started.
