### ISSUE TITLE
Types for BrowserOptions.transport don't match code

### ISSUE THREAD

**Issue by mamacdon** [amplitude/Amplitude-TypeScript#387]
Consider the type definitions for [BrowserOptions](https://github.com/amplitude/Amplitude-TypeScript/blob/4fd7691/packages/analytics-types/src/config/browser.ts#L55C1-L57) and [TransportType](https://github.com/amplitude/Amplitude-TypeScript/blob/4fd7691/packages/analytics-types/src/transport.ts#L8C1-L12): 

```ts
export enum TransportType {
  XHR = 'xhr',
  SendBeacon = 'beacon',
  Fetch = 'fetch',
}
```
```ts
export interface BrowserOptions extends Omit<Partial<BrowserConfig>, 'apiKey'> {
  transport?: TransportType | keyof typeof TransportType;  // <---- note this
}
```

## Expected Behavior
Based on the type signatures above, I'd expect this code to configure the Amplitude client using the beacon transport.

```ts
import * as amplitude from '@amplitude/marketing-analytics-browser';

amplitude.init('……', undefined, {
  transport: 'SendBeacon',  // <--- passing keyof typeof TransportType
});
```

## Current Behavior
The default transport (fetch) is always used

## Possible Solution
The problem here is a mismatch between [the code here](https://github.com/amplitude/Amplitude-TypeScript/blob/4fd7691/packages/analytics-browser/src/config.ts#L260-L266) and the type definition shown above.

Either remove the `| keyof typeof TransportType` part from the type definition, or fix the code to something like this (not tested, but you get the idea)

```ts
export const createTransport = (transport?: TransportType | keyof typeof TransportType) => {
  if (transport === TransportType.XHR || TransportType[transport] === TransportType.XHR) {
    return new XHRTransport();
  }
  if (transport === TransportType.SendBeacon || TransportType[transport] === TransportType.SendBeacon) {
    return new SendBeaconTransport();
  }
  return getDefaultConfig().transportProvider;
};
```

## Steps to Reproduce
1. See above
2.
3.
4.

## Environment
- JS SDK Version: `@amplitude/analytics-browser` v1.10.2
- Installation Method: NPM install
- Browser and Version: Chrome 113

**Comment by Mercy811** [comment]
Hi @mamacdon, the key of `TransportType.SendBeacon` use be 'beacon' so the following should work:

```
import * as amplitude from '@amplitude/marketing-analytics-browser';
import {TransportType} from '@amplitude/analytics-types';

amplitude.init('……', undefined, {
  transport: "beacon" as TransportType // <--- passing keyof typeof TransportType
});

amplitude.init('API_KEY', 'example.react.user@amplitude.com', {
  transport: TransportType.SendBeacon // <--- passing TransportType
});
```
