### ISSUE TITLE
Domain proxying not applying when using the `domain` option

### ISSUE THREAD

**Issue by deiay** [amplitude/Amplitude-TypeScript#388]
## Expected Behavior
When initializing the browser client with the `domain` attribute, all amplitude requests are meant to be proxied via the url specified in the domain option. I'm noticing that this is no longer happening after migrating from using the old  `amplitude-js` library to `@amplitude/analytics-browser` v1.9.1.

## Current Behavior
When using the init(apiKey, options) with the `domain` option, requests are still being sent the to amplitude API url instead of being proxied through the url i specified. Since my app doesn't allow external requests, I'm unable to use the amplitude browser client:
<img width="1048" alt="Screen Shot 2023-05-23 at 3 41 05 PM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/7328115/d1367259-55f6-4d3f-82a3-92704f29b508">

## Steps to Reproduce

1. Setup the client with: 
```typescript

let amplitudeClient: Types.BrowserClient
let initialized = false

const initialize = async () => {
	amplitudeClient = createInstance()

	const { promise } = amplitudeClient.init(
		process.env.NEXT_PUBLIC_AMPLITUDE_API_KEY,
		undefined, // null userid on init
		{
			// proxying requests to through our API server to prevent browsers from blocking these requests
			domain: `${window.location.host}/amplitude`,
			// for analytics to work for localhost, we need to allow non secure http requests
			// amplitude will use the current protocol to determine if it should use https or http
			cookieSecure: false,
		}
	)
	await promise
	initialized = true

	const identification = new Identify()
	identification.set('env', 'prod')
	identification.set('app', 'myapp')

	const { promise: identifypromise } = amplitudeClient.identify(identification)
	await identifypromise
	return Promise.resolve()
}

```
2.  Fire an event with:
```typescript
const trackEvent: ITrackEvent = async (eventName, params) => {
	if (!initialized) {
		await initialize()
	}

	const { promise } = amplitudeClient.logEvent(eventName, params)

	await promise
	return Promise.resolve()
}
```
3. Check networks logs to see if any requests were made to `https://api2.amplitude.com`

## Environment
- JS SDK Version: `1.10.3`
- Installation Method: `yarn`
- Browser and Version: `Version 113.0.5672.126`

**Comment by Mercy811** [comment]
Hi @deiay, `configuration.domain` is used to set the top level domain for cookies. 

> When initializing the browser client with the domain attribute, all amplitude requests are meant to be proxied via the url specified in the domain option. I'm noticing that this is no longer happening after migrating from using the old amplitude-js library to @amplitude/analytics-browser v1.9.1.

Did you successfully set the proxy by setting `configuration.domain`? It's unlikely that would happen. 

> JS SDK Version: 1.10.3
The current SDK version you are using is really old. It's highly recommended to upgrade to the latest version or migrate to TS SDK. JS SDK is in maintenance status and only accepts bug fixes. 

Here is an [example](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#custom-http-client) of how to set a proxy using TS SDK.

Please let me know if you have any other questions.

**Comment by deiay** [comment]
Ah yea, setting the `options.domain` proxied requests on the old SDK (`amplitude-js`). Thanks for the clarification, I'll switch to using this method
