### ISSUE TITLE
amplitude dashboard (deep link): open the user page via userId rather than amplitude_id 

### ISSUE THREAD

**Issue by dht** [amplitude/Amplitude-TypeScript#389]
This screen leads to a specific user card:
[https://analytics.amplitude.com/[COMPANY]/project/[PROJECT]/search/amplitude_id%3D6257241213232](https://analytics.amplitude.com/%5BCOMPANY%5D/project/%5BPROJECT%5D/search/amplitude_id%3D6257241213232)
How can I open the same screen with a userId rather than an amplitude_id.

If it's not possible is there a way to get the amplitude id of the user from the Browser SDK.
I want power users (our company's employees) to be able to open their own user page easily from the web app to debug analytics events more easily.

**Comment by Mercy811** [comment]
Hi @dht, I would like to close this thread as it is duplicated with https://github.com/amplitude/Amplitude-JavaScript/issues/592

**Comment by dht** [comment]
Yes, apologies, I got to the repositories from an NPM search and wrongly assumed they are maintained by different maintainers.
Now I see they are both under the amplitude official organization.
