### ISSUE TITLE
How to set deviceIdFromUrlParam & apiEndpoint

### ISSUE THREAD

**Issue by dalenguyen** [amplitude/Amplitude-TypeScript#392]
## Summary

In the previous version, I load ampli with these options.

```
 * Required dependencies: amplitude-js@^8.21.0
 * Tracking Plan Version: 59
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli
```

```
ampli.load({
        environment,
        client: {
          options: {
            deviceIdFromUrlParam: true,
            trackingOptions: { ip_address: false },
            apiEndpoint: 'https://example.com'
          },
        },
      })
```

However, in the new version I couldn't find their replacement. Could you please have a look at it?

```
 * Required dependencies: @amplitude/analytics-browser@^1.3.0
 * Tracking Plan Version: 82
 * Build: 1.0.0
 * Runtime: browser:typescript-ampli-v2
```

```
ampli.load({
   environment,
   client: {
          configuration: {
              trackingOptions: {
                   ipAddress: false,
                   // deviceIdFromUrlParam & apiEndpoint ?????
               }
           }
    },
})
```

Thanks,

**Comment by Mercy811** [comment]
Hi @dalenguyen, you can refer to [Amplitude Browser SDK Migration](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/migration/#configuration) and [Cross-site tracking](https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#cross-domain-tracking)
- `apiEndpoint` -> `serverUrl`
- `deviceIdFromUrlParam` is removed in configuration. However, if the deviceId isn't provided with the init like init('API_KEY', null, { deviceId: 'custom-device-id' }), then it automatically fallbacks to use URL parameter.

**Comment by dalenguyen** [comment]
Awesome. Thanks for your info 🙏
