### ISSUE TITLE
ReferenceError: location is not defined

### ISSUE THREAD

**Issue by hugihlynsson** [amplitude/Amplitude-TypeScript#397]
## Expected Behavior

The package should build in non-browser environment

## Current Behavior

After [upgrading from 1.10.3 to 1.10.4](https://github.com/avohq/docs/pull/911) we get a `ReferenceError: location is not defined` when building our project as part of Node.js, both in Vercel and locally. Presumably it's caused by the @amplitude/plugin-page-view-tracking-browser bump to 0.8.1, more specifically https://github.com/amplitude/Amplitude-TypeScript/commit/31d6435b0f50da89302e83431a6fb5c1b46ec71b

## Possible Solution
Add a null-check for `location`

## Steps to Reproduce
See PR: https://github.com/avohq/docs/pull/911

## Environment
- JS SDK Version: 1.10.4
- Installation Method: Yarn

**Comment by kevinpagtakhan** [comment]
Should be fixed in @amplitude/analytics-browser@1.10.5

**Comment by hugihlynsson** [comment]
Thanks @kevinpagtakhan, I appreciate the fast turnaround time!
