### ISSUE TITLE
Missing setUserProperties in analytics-browser

### ISSUE THREAD

**Issue by nextglabs** [amplitude/Amplitude-TypeScript#410]
## Summary

In Amplitude-Javascript, there is a [`setUserProperties`](https://amplitude.github.io/Amplitude-JavaScript/#amplitudeclientsetuserproperties) function which seems to be missing in `@amplitude/analytics-browser`. Is this intentional?

On the other hand, I see that `event.set()` exists, is it a replacement?

**Comment by justin-fiedler** [comment]
Hi @nextglabs thanks for using Amplitude.

In the Amplitude-TypeScript SDK you should use `identify()` to set user properties.

https://www.docs.developers.amplitude.com/data/sdks/typescript-browser/#user-properties
