### ISSUE TITLE
Introduce sessionStorage for identityStorage option

### ISSUE THREAD

**Issue by henninghaakonsen** [amplitude/Amplitude-TypeScript#434]
Hi! Is it possible to copy this feature to this sdk? https://github.com/amplitude/amplitude-javascript/issues/317

## Summary

Se issue: https://github.com/amplitude/amplitude-javascript/issues/317

## Motivations

Because of privacy we want to limit our users to sessions. While localStorage is an improvement over cookies, we would love to use sessionStorage for our use.

**Comment by kevinpagtakhan** [comment]
Hi @henninghaakonsen, thank you for choosing Amplitude. We're currently working with @nutgaard to get this feature in. The PR is looking good so far. I'm hoping we can get it merged before the week ends.

**Comment by henninghaakonsen** [comment]
> Hi @henninghaakonsen, thank you for choosing Amplitude. We're currently working with @nutgaard to get this feature in. The PR is looking good so far. I'm hoping we can get it merged before the week ends.

Great! Nicklas and I are on the same team and we are looking forward to use the new feature!

**Comment by kevinpagtakhan** [comment]
Hi, this feature is now available starting v2.1.0! Thank you for your contributions!
