### ISSUE TITLE
Module not found: Can't resolve '@amplitude/analytics-core'

### ISSUE THREAD

**Issue by TheMechanic** [amplitude/Amplitude-TypeScript#459]
Hi,

I'm not able to make it work, when I launch my nextjs app, it crashes, because : Module not found: Can't resolve '@amplitude/analytics-core'. Any ideas ?

I tried to install it as dependency,  but doesn't fix the issue

thank you !

## Expected Behavior

It shouldn't crash

## Current Behavior
It crashes

## Possible Solution
missing dependency in the lib ?

## Steps to Reproduce
Just create a basic nextjs app, then add @amplitude/analytics-browser 2.1.0 and init amplitude

1.
2.
3.
4.

## Environment
- JS SDK Version: 2.1.0
- Installation Method: yarn / import
- Browser and Version: Chrome 114.0.5735.133 (Build officiel) (arm64)

**Comment by TheMechanic** [comment]
Update : I fiexed it by setting this in my .yarnrc.yml :
` packageExtensions:
    '@amplitude/plugin-web-attribution-browser@*':
        dependencies:
          '@amplitude/analytics-core': '*'
`

So it is a missing dependencies / misconfiguration in @amplitude/plugin-web-attribution-browser package...

**Comment by Mercy811** [comment]
Hi @TheMechanic, glad to hear that your problem has been solved. Can I know Which SDK you are using and which documentation you are following to improve our dev doc?
