### ISSUE TITLE
App crashing after ota by amplitude library

### ISSUE THREAD

**Issue by Harsh-Pratap-Singh1** [amplitude/Amplitude-TypeScript#467]
App Crashing while reloading after an OTA update and throws this error - NativeArgumentsParseException
AmplitudeReactNative.getApplicationContext got 3 arguments, expected 2

**Comment by justin-fiedler** [comment]
Hi @Harsh-Pratap-Singh1 thanks for using Amplitude.

We will look into the issue. Can you please provide the version of the SDK giving you the error? Thanks

**Comment by natphysnahagey** [comment]
@justin-fiedler I'm seeing this on version `1.3.0`

```
"@amplitude/analytics-react-native@^1.3.0":
  version "1.3.0"
  resolved "https://registry.yarnpkg.com/@amplitude/analytics-react-native/-/analytics-react-native-1.3.0.tgz#2bb160ad816d7498c3c5ce2ff3c3753d21240425"
  integrity sha512-48qaiihLpvoo06bAOHyCLyXBk/mMlTonzZEyAO9EEFCXxI6q7jpjL6+wavlwCrVhjrt07W55kqgWoUn8MxXxpw==
  dependencies:
    "@amplitude/analytics-client-common" "^1.1.0"
    "@amplitude/analytics-core" "^1.2.0"
    "@amplitude/analytics-types" "^1.3.0"
    "@amplitude/ua-parser-js" "^0.7.31"
    "@react-native-async-storage/async-storage" "^1.17.11"
    tslib "^2.4.1"
```

**Comment by justin-fiedler** [comment]
Thanks @natphysnahagey. A couple more questions for you.

1. What OS is this happening on (Android, iOS, both?) 
2. Can you provide some details on how the OTA update process works in your application.

If this error is only happening in iOS, could you please make sure the latest native code is installed.
```sh
cd ios
pod install
```

**Comment by justin-fiedler** [comment]
Hi @natphysnahagey based on the [Expo documentation OTA updates do not support native code changes](https://docs.expo.dev/eas-update/runtime-versions/). We changed both JS and native code in `@amplitude/analytics-react-native@1.3.0`.

Setting "runtimeVersion" should help - [Avoiding crashes with incompatible updates](https://docs.expo.dev/eas-update/runtime-versions/#avoiding-crashes-with-incompatible-updates)
