### ISSUE TITLE
TypeError: globalScope.addEventListener is not a function

### ISSUE THREAD

**Issue by nabusman** [amplitude/Amplitude-TypeScript#500]
## Expected Behavior
Start the dev server without error

## Current Behavior
After installing I tried running `npm run dev` and got the following error:

TypeError: globalScope.addEventListener is not a function
    at Object.<anonymous> (/.../node_modules/@amplitude/plugin-page-view-tracking-browser/src/page-view-tracking.ts:78:21)
    at step (/.../node_modules/@amplitude/plugin-page-view-tracking-browser/node_modules/tslib/tslib.js:195:27)
    at Object.next (/.../node_modules/@amplitude/plugin-page-view-tracking-browser/node_modules/tslib/tslib.js:176:57)
    at /.../node_modules/@amplitude/plugin-page-view-tracking-browser/node_modules/tslib/tslib.js:169:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/.../node_modules/@amplitude/plugin-page-view-tracking-browser/node_modules/tslib/tslib.js:165:16)
    at Object.setup (/.../node_modules/@amplitude/plugin-page-view-tracking-browser/src/page-view-tracking.ts:71:63)
    at Timeline.<anonymous> (/.../node_modules/@amplitude/analytics-core/src/timeline.ts:28:23)
    at step (/.../node_modules/@amplitude/analytics-core/node_modules/tslib/tslib.js:195:27)
    at Object.next (/.../node_modules/@amplitude/analytics-core/node_modules/tslib/tslib.js:176:57)

## Steps to Reproduce
1. `npm install @amplitude/analytics-browser`
2. `npm run dev`

## Environment
My dependencies in package.json:
  "@amplitude/analytics-browser": "^2.1.2",
  "next": "12.1.6",
  "nextjs-cors": "^2.1.2",
  "ngrok": "^4.3.1",
  "react": "^18.1.0",
  "react-dom": "18.1.0",
  "react-markdown": "^8.0.7",
  "sharp": "^0.30.7",
  "swr": "^1.3.0"

**Comment by Mercy811** [comment]
Hi @nabusman, for NextJS we usually recommend using the Amplitude [Node SDK](https://www.docs.developers.amplitude.com/data/sdks/typescript-node/). This is because NextJS code may be run on both on the client (browser) and the server (SSR).

Hope this helps and let me know if it doesn't!

**Comment by glung** [comment]
@Mercy811 I am also facing this issue. And I have some questions too.

- Ideally, in the server-side case, tracking should be triggered on the client side. wdyt?
- The plugin `@amplitude/plugin-page-view-tracking-browser/` is the trigger for the issue. Would this plugin work with the Node SDK? And in general, does the NodeSDK work on the browser?

**Comment by glung** [comment]
@Mercy811 what do you think of the following approach? 

- use the browser-sdk and send all analytics from the browser when the component mound (`React.useEffect(,track [])`)
- don't load ampli on the server-side (`if (typeof window === "undefined") return;`)


I don't think that the NodeSDK is a good fit for a NextJS app

**Comment by Mercy811** [comment]
Hi @glung, yes if you want to use `@amplitude/plugin-page-view-tracking-browser` plugin, you have to use the browser SDK because the Node SDK doesn't support that. But have to be carefully and make sure that the the browser SDK only runs on client side as it include platform specific code which can not run on server side. Here is [an example Next.js app](https://github.com/amplitude/Amplitude-TypeScript/tree/main/examples/browser/next-app) using browser SDK. Hope this is helpful.

**Comment by ADTC** [comment]
@Mercy811 I followed your recommendation yesterday and switched from Browser SDK to Node SDK. The errors disappeared but Amplitude is no longer capturing events.

But now you have crossed it out.

What is the correct recommendation here? How do we install the SDK in a Next.js 13 project which has both server and client? It's attempting to load Browser SDK in server, which fails obviously, but it looks like Node SDK doesn't work as expected on the client.

**Comment by georgewitteman** [comment]
I am also running into this issue. Could an option be added to completely disable this plugin (e.g. [here](https://github.com/amplitude/Amplitude-TypeScript/blob/81c39c33031554f58d1f02e374517b0ee2901c37/packages/analytics-browser/src/browser-client.ts#L112C18-L112C18))? The other default plugins are all wrapped in [a check to see if they are needed](https://github.com/amplitude/Amplitude-TypeScript/blob/81c39c33031554f58d1f02e374517b0ee2901c37/packages/analytics-browser/src/browser-client.ts#L100) before being loaded.

**Comment by j-wing** [comment]
@Mercy811 Checking in on this, are there any plans to fix this issue on the Amplitude side? NextJS renders components on the server side and this crash happens during import, so even if we don't init Amplitude on the server side it still crashes. It seems like it totally breaks recent versions of Amplitude in NextJS without the workaround @ADTC shared. 😔

**Comment by Mercy811** [comment]
Hi @georgewitteman, thanks for your suggestion and choosing Amplitude. We've re-prioritize this and I will keep you updated.

**Comment by Mercy811** [comment]
Hi @georgewitteman, `@amplitude/analytics-browser@2.4.1` supports to not install the page view plugin by either `config.defaultTracking = false` or `config.defaultTracking.pageViews = false`.
