### ISSUE TITLE
Cookie options attribute from `init` call mostly not respected

### ISSUE THREAD

**Issue by michal-filip** [amplitude/Amplitude-TypeScript#551]
While attempting to modify cookie options, I noticed that despite setting the corresponding configuration options, the cookies are still generated with same original attributes.

## Expected Behavior
I expected the `sameSite: 'None'` and `secure: true` attributes to be applied to newly created cookies

## Current Behavior
Original attributes `sameSite: 'Lax'` and `secure: false` are still set.

## Possible Solution
It looks like the object spreading on the following line might be done in an incorrect location, keeping most properties fixed and not overridable:
https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-browser/src/config.ts#L189

## Steps to Reproduce
1. add the following code to be executed in the browser on page load
```
amplitude.init(<apikey>, {
        // ...
        cookieOptions: {
          sameSite: 'None',
          secure: true,
        }
})
```
2. make sure no `AMP_` cookies are set in the browser
3. load the application
4. check the attributes of the auto-created cookies - observe that sameSite is 'Lax' and secure is false

## Environment
- JS SDK Version: 2.2.0
- Installation Method: yarn
- Browser and Version: Chrome 114.0.5735.106

**Comment by alex-geopro** [comment]
Is this still an issue?  I'm initializing the browser sdk like this:

```
amplitude.init('f01c77366af58e34a071913e9f75ab7f', { 
        logLevel: 4,
        cookieOptions: {
          sameSite: 'None',
          secure: true,
        }
      }
```

And the cookie still has sameSite: 'Lax' (after deleting cookies and trying again)
