### ISSUE TITLE
Unable to customize pageview eventType

### ISSUE THREAD

**Issue by alex-geopro** [amplitude/Amplitude-TypeScript#596]
## Expected Behavior

I expected the default tracking eventType for pageviews to change from the default `[Amplitude] Page Viewed` to the value i set.

## Current Behavior

It stayed at the default value.

## Possible Solution

Not sure.

## Steps to Reproduce

See: https://www.docs.developers.amplitude.com/data/sdks/browser-2/#tracking-default-events

Initialize it like this:

```
      amplitude.init('<api_key>', '<user_id>', { 
        defaultTracking: {
          pageviews: {
            eventType: 'pageview'
          }
        }
      });
```

## Environment
- Browser SDK Version: 2.2.3
- Installation Method: <script/> tag

<img width="794" alt="Screenshot 2023-10-02 at 6 08 20 PM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/144632814/0f8a18db-768b-4c45-a27c-4bfeaf3a8d5d">

**Comment by alex-geopro** [comment]
Ok I got this working, I had a typo, it should be `pageViews` not `pageviews`.

Follow on question: is there a way to customize the event property names? The default ones seem super verbose and have spaces in them etc, seems very non-standard.

<img width="487" alt="Screenshot 2023-10-02 at 6 11 47 PM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/144632814/3c8d9b82-cdc4-4ee6-9078-00205eda92d6">

**Comment by alex-geopro** [comment]
Also, how can I configure/change the `eventType` for other default events, like session started etc?

**Comment by Mercy811** [comment]
Hi @alex-geopro, thanks for choosing Amplitude. Afaik, the SDK doesn't support customizing event name or event property name unfortunately.

**Comment by alex-geopro** [comment]
Hi @Mercy811 it definitely does, I have it working for the pageview event. see attached:

<img width="1215" alt="Screenshot 2023-10-03 at 11 20 29 AM" src="https://github.com/amplitude/Amplitude-TypeScript/assets/144632814/9308f3d7-ea63-415e-9287-692b3a21fb01">

**Comment by Mercy811** [comment]
Other default tracking events are not supported to change event type except pageViews. Please refer to the typings [here](https://github.com/amplitude/Amplitude-TypeScript/blob/25962cd2ee3593eb2ed4ffd6c34f16c02a11e319/packages/analytics-types/src/config/browser.ts#L30-L36).

**Comment by Mercy811** [comment]
Hi @alex-geopro, although there is no direct configurations over default events, you can customize it by a enrichment plugin. Please refer to the [docs](https://www.docs.developers.amplitude.com/data/sdk-plugins/) and an example [here](https://www.docs.developers.amplitude.com/data/sdks/browser-2/#enrichment-plugin). Simply rewrite the event type there if the current event is a session event or other default events you want to rename.

**Comment by alex-geopro** [comment]
Hi, as I showed there is direct configuration over the default pageview
eventType, I showed the code to do it, and a screenshot of the result, and
its mentioned in your docs.

Thanks for the suggestion on rewriting the other eventTypes which don't
have this feature (I assume)
