### ISSUE TITLE
unknown statement of type ForOfStatement

### ISSUE THREAD

**Issue by reflash** [amplitude/Amplitude-TypeScript#614]
## Expected Behavior
Build completes with no errors

## Current Behavior
error: ../node_modules/@amplitude/analytics-react-native/src/config.ts: /<root>/node_modules/@amplitude/analytics-react-native/src/config.ts: unknown Statement of type "ForOfStatement"

## Steps to Reproduce

1. Installed and configured react native sdk as per the documentation
2. Run project build

## Environment
- JS SDK Version: 1.4.5
- Installation Method: yarn
- Browser and Version: RN 0.72.4

**Comment by justin-fiedler** [comment]
Hi @reflash, thanks for choosing Amplitude.

I have not seen this error before. Doing some research it seems this could be an issue with your babel configuration.

Could you please give this solutions a try and let us know if that fixes the issue?
* https://github.com/parcel-bundler/parcel/issues/1269#issuecomment-496799295
* https://stackoverflow.com/questions/76154276/unknown-statement-of-type-forofstatement-when-trying-to-run-an-npm-library

Thank you!
