### ISSUE TITLE
Last version issue

### ISSUE THREAD

**Issue by rmoralp** [amplitude/Amplitude-TypeScript#640]
## Expected Behavior
Do not break.

## Current Behavior
![image](https://github.com/amplitude/Amplitude-TypeScript/assets/5390428/93415838-3272-4f4b-a577-d29cfa69d51d)

Check this:
https://github.com/amplitude/Amplitude-TypeScript/commit/c820279cbef2123d890beb7861d7edbbc3926f6e

## Steps to Reproduce
Install last version of `@amplitude/analytics-browser`

## Environment
- JS SDK Version: 
- Installation Method: 
- Browser and Version:

**Comment by kevinpagtakhan** [comment]
Hi @rmoralp thank you for reporting this issue! Can you share the versions of @amplitude/* packages in your yarn.lock or package-lock.json?

**Comment by rmoralp** [comment]
The error occurred in `@amplitude/analytics-browser@2.3.7`, to fix it we had override (with npm) some sub dependencies:
```
  "overrides": {
    "@amplitude/analytics-browser": {
      "@amplitude/analytics-client-common": "2.0.9",
      "@amplitude/analytics-core": "2.1.2"
    }
  },
```
Today I tried last version `@amplitude/analytics-browser@2.3.8` and the problems seems to be fixed.
