### ISSUE TITLE
transportProvider isn't available in init in analytics-browser v2

### ISSUE THREAD

**Issue by antsav** [amplitude/Amplitude-TypeScript#650]
### What happened?

package.json:
`    @amplitude/analytics-browser": "^2.3.8",`
    

index.ts: 
```
    amplitude.init(amplitudeApiKey, clientId, {
       transportProvider: new FetchTransport(), // < this method listed in documentation, but isn't available in SDK
    })
```

### Typescript error

```shell
Object literal may only specify known properties, and 'transportProvider' does not exist in type 'Omit<Partial<ExternalBrowserConfig>, HiddenOptions>'
```

**Comment by admmasters** [comment]
Yeah any update as to why this was dropped in 2.0 - this is what I wanted to use for proxying to `http://localhost:3000/amplitude` in case there is a v2 way of achieving that.

**Comment by Mercy811** [comment]
Hi @antsav, `config. transportProvider` is in `HiddenOptions` so it's not configurable. I will update the docs to reflect it. You can use `config.fetch` instead. 
<img width="622" alt="image" src="https://github.com/amplitude/Amplitude-TypeScript/assets/31029607/919e3654-4437-4314-8152-c85dbd199e10">

```
amplitude.init('API_KEY', 'example.react.user@amplitude.com', {
  transport: 'fetch',
});
```
