### ISSUE TITLE
Issue building with Gradle 8 and RN 0.73.4

### ISSUE THREAD

**Issue by victor-chan-groundswell** [amplitude/Amplitude-TypeScript#665]
It seems that, when running react native 0.73.4, along with building with gradle 8, I ran into this error message.

A problem occurred configuring project ':amplitude_analytics-react-native'.
> com.android.builder.errors.EvalIssueException: defaultConfig contains custom BuildConfig fields, but the feature is disabled.
  To enable the feature, add the following to your module-level build.gradle:
  `android.buildFeatures.buildConfig true`

So I went ahead and went down the rabbit hole and looked up a way to enable this....
https://stackoverflow.com/questions/74634321/fixing-the-build-type-contains-custom-buildconfig-fields-but-the-feature-is-di

When I do that, however, then it craps out where on the react native side, with the following error:

A problem occurred evaluating project ':app'.
> Failed to apply plugin 'com.facebook.react'.
   > The value for property 'languageVersion' is final and cannot be changed any further.

I have already flagged this issue on the react-native github, but I'm not sure whether this needs to be looked at on this end or react-natives... either way it does not build correctly.

https://github.com/facebook/react-native/issues/41580

**Comment by Charles-Johnson** [comment]
I'm facing a similar issue when upgrading to RN 0.73.4 as part of upgrading a managed expo app to SDK 50. I was able to fix the `BuildConfig` issue by adding the lines to this packages `android/build.gradle`
```gradle
android {
  // existing code
  buildFeatures {
    buildConfig = true
  }
  // existing code
}
```
I still got the `languageVersion` error but also this:
```
A problem occurred configuring project ':app'.
> compileSdkVersion is not specified. Please add it to build.gradle
```

In my app's `android/build.gradle` (which is generated by `expo prebuild`) there's already 
```gradle
buildscript {
  ext {
    compileSdkVersion = Integer.parseInt(findProperty('android.compileSdkVersion') ?: '33')
    // more stuff
  }
  // more stuff
}
```

**Comment by NomanGul** [comment]
this patch worked for me -> https://github.com/amplitude/Amplitude-TypeScript/pull/617

**Comment by nmongiya** [comment]
That patch #617 is not working for me :(

**Comment by LekZ974** [comment]
Same issue here. Any update?? The patch is not working for me too

**Comment by Mercy811** [comment]
RN 0.x is at branch v1.x and this issue has already been fixed in https://github.com/amplitude/Amplitude-TypeScript/pull/533
