### ISSUE TITLE
How do you track the IP Address?

### ISSUE THREAD

**Issue by valgen** [amplitude/Amplitude-TypeScript#672]
Hi there,

Do you actually take into account X-Forwarded-For when trackingOptions ipAddress is set to true?

`
amplitude.init(AMPLITUDE_API_KEY, {
  trackingOptions: {
    ipAddress: true
  }
});
`

If not, please can you tell me how to do so using the JS SDK?
https://www.docs.developers.amplitude.com/data/sdks/browser-2/#optional-tracking

**Comment by izaaz** [comment]
@valgen - yes, we get the source ip address on the server side. When the `ipAddress`  tracking option is set to false, we discard the ip address on the server side and don't convert it to city/country properties.

**Comment by valgen** [comment]
@izaaz Can you be more specific and tell me if you actually use **X-Forwarded-For** to make your best-effort attempt to discover the originating IP?

**Comment by izaaz** [comment]
Yes @valgen - yes, that header gets used to determine the origin ip.
