### ISSUE TITLE
Cannot find module error when trying to init library

### ISSUE THREAD

**Issue by shanti2530** [amplitude/Amplitude-TypeScript#69]
I installed the library in an angular project using npm, however when I init the library with my API Key I get the following error during compilation 

Import in service 
`import { init } from '@amplitude/analytics-browser';`

Code in service constructor
`init(API_KEY);`

Compilation error
> Error: node_modules/@amplitude/analytics-browser/lib/esm/utils/snippet-helper.d.ts:1:43 - error TS2307: Cannot find module '../typings/browser-snippet' or its corresponding type declarations.
1 import { QueueProxy, InstanceProxy } from '../typings/browser-snippet';

Can you please help?

**Comment by kevinpagtakhan** [comment]
Hi @shanti2530! Thanks for submitting an issue. It looks like the typings directory isn't getting included in the build files which is causing this error. Let me take a look further and put out a fix!

cc @dnshi

**Comment by kevinpagtakhan** [comment]
Hi @shanti2530, this should be fixed in the new version we just released. Let us know if there's anything else you see 👍

**Comment by shanti2530** [comment]
Hi @kevinpagtakhan, thanks for the quick reply. I've just updated the library and the app is now compiling successfully.
