### ISSUE TITLE
IP Address Tracked even when disabled

### ISSUE THREAD

**Issue by FirstVertex** [amplitude/Amplitude-TypeScript#701]
## Expected Behavior

Expect that the IP Address should not be tracked when it has been disabled via options.

## Current Behavior

The IP Address was tracked even when it was explicitly disabled in `amplitude.init`

## Possible Solution

This will require a code fix in `@amplitude/analytics-browser`

## Steps to Reproduce

1. Set [`trackingOptions.ipAddress`](https://amplitude.github.io/Amplitude-TypeScript/interfaces/_amplitude_analytics_browser.Types.TrackingOptions.html#ipAddress) to `false`
2. call amplitude.init with these trackingOptions <img width="431" alt="image" src="https://github.com/amplitude/Amplitude-TypeScript/assets/2387520/7be72d6b-7566-4c4a-be31-df52db485856">
3. track any event `amplitude.track('testEvent')`
4. open the [Analytics dashboard](https://app.amplitude.com/analytics/ryan-llc/project/438390/search/amplitude_id%3D636550779204)
5. in the Users and Sessions tab, User Lookup table, find the event that you created in step 3
6. click the User ID to get to the User Look-up page
7. scroll to the bottom of the outer scroll and the bottom of the bottom right inner scroll
8. under the section titled "Other", notice the IP Address is tracked even though it was explicitly configured as false in the init trackingOptions in step 2

## Environment
- JS SDK Version: 
`"@amplitude/analytics-browser": "2.6.1"`
- Installation Method: 
- npm
- Browser and Version: 
- Chrome Version 123.0.6312.86 (Official Build) (64-bit)

**Comment by FirstVertex** [comment]
Language was also tracked, even when it was disabled in the example above.

Suggest an audit of all `trackingOptions` because this is just the ones I have tested.

**Comment by izaaz** [comment]
@FirstVertex thank you for raising this issue. 

I tried it out locally on my test app and noticed that ip address was not collected when the setting was set to false. Generally, when the flag is set to true (which it is by default, you'll notice that we add `'ip_address': '$remote'` in the event payload. This instructs the server to use the ipaddress from the request to capture ip information. And when set to `false` this field will not be populated. Can you please check your network tab to see if its behaving differently?

Also - a side note (which is probably what you're running into). When the ip tracking is disabled, it disables ip tracking from that point going forward for that user. So any ip information that was collected so far will not be dropped. So you'll continue to see a stale ip address on that user.

If you try instrumenting with ip disabled on a fresh user, you'll notice that the ip information is not captured. Here's a screenshot from my test user

![image](https://github.com/amplitude/Amplitude-TypeScript/assets/4400939/701e6982-8568-4c25-af3f-e5061ffc28f1)

Again the above is what is expected. If you see something different, I'd be happy to dig deeper.
