### ISSUE TITLE
Since the @amplitude/session-replay-browser 1.6.1 update, nextjs fails to build due to Error [ERR_REQUIRE_ESM].

### ISSUE THREAD

**Issue by jylee9937** [amplitude/Amplitude-TypeScript#784]
## Expected Behavior
nextjs project build

## Current Behavior
An error is occurring. The error happens regardless of the version, and it has been occurring since @amplitude/plugin-session-replay-browser version 1.6.1. Downgrading to other versions doesn't resolve the issue. But remove that, I can build nextjs project.

```
info  - Need to disable some ESLint rules? Learn more here: https://nextjs.org/docs/basic-features/eslint#disabling-rules
info  - Linting and checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/a123123/WebstormProjects/Client-HomePage-Next/node_modules/@medv/finder/finder.js from /Users/a123123/WebstormProjects/Client-HomePage-Next/node_modules/@amplitude/session-replay-browser/lib/cjs/hooks/click.js not supported.
Instead change the require of finder.js in /Users/a123123/WebstormProjects/Client-HomePage-Next/node_modules/@amplitude/session-replay-browser/lib/cjs/hooks/click.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/a123123/WebstormProjects/Client-HomePage-Next/node_modules/@amplitude/session-replay-browser/lib/cjs/hooks/click.js:6:16) {
  code: 'ERR_REQUIRE_ESM'
}

```

## Steps to Reproduce
1. make nextjs project
2. setup @amplitude/plugin-session-replay-browser in _app.tsx
3. necxt build

## Environment
- JS SDK Version: Node 20.10.0 + nextjs 13.1.1 + @amplitude/analytics-browser 2.6.2
- Installation Method: Yarn 
- Browser and Version: n/a

**Comment by purepetfood** [comment]
Same issue here

**Comment by anders2410** [comment]
We are also experiencing the same issues using Next.js

**Comment by sharath-sb** [comment]
Same here

**Comment by lewgordon-amplitude** [comment]
Hey all. Thanks for reporting this. We're looking into it.

**Comment by lewgordon-amplitude** [comment]
I just published a new version `@amplitude/plugin-session-replay-browser@1.6.3`. Does this fix the issue?

**Comment by jylee9937** [comment]
Hi Lew Gordon, Your help is greatly appreciated, and everything is working perfectly now.
Thank you 👍
