### ISSUE TITLE
SecurityError: Operation is insecure

### ISSUE THREAD

**Issue by ashishkpoudel** [amplitude/Amplitude-TypeScript#788]
We have started seeing Operation is insecure in our bugsnag error reporting. We use amplitude with next js 13

## Expected Behavior
Ability to use amplitude client without the Security Error

## Current Behavior
Amplitude client `"@amplitude/analytics-browser": "^2.3.2"` is not able to access local storage.

## Steps to Reproduce
![Screenshot from 2024-06-23 18-52-30](https://github.com/amplitude/Amplitude-TypeScript/assets/23501033/69fee2d9-f6f7-46c2-94c4-6a13738dafbe)

## Environment
- JS SDK Version: "@amplitude/analytics-browser": "^2.3.2",
- Installation Method: Yarn
- Browser and Version: Chrome Mobile 126.0, Mobile Safari 16.6.0, Mobile Safari 17.5.0

**Comment by Mercy811** [comment]
Hi @ashishkpoudel, `@amplitude/analytics-browser@2.9.3` should fix this issue.

**Comment by ashishkpoudel** [comment]
> Hi @ashishkpoudel, `@amplitude/analytics-browser@2.9.3` should fix this issue.

Thank you for the fix
