### ISSUE TITLE
Session replay standalone CDN script initialisation

### ISSUE THREAD

**Issue by steverob** [amplitude/Amplitude-TypeScript#799]
## Summary

I'm looking to use the CDN version of the standalone session replay plugin. I am unable to figure out how to initialise it with the API key and start recording. 

I'm using rudderstack as my instrumentation framework and it can give me sessionId & deviceId.

I'm only able to call the "plugin" function on the session replay object made available via the CDN script and it does not seem to take api key.

**Comment by kwalker3690** [comment]
@steverob Thanks for calling our attention here, it looks like our docs are missing instructions for the Standalone Session Replay SDK initialization via script tag. I'll make updates to our docs, but in the meantime you can use the following script:
```
<script src="https://cdn.amplitude.com/libs/plugin-session-replay-browser-1.4.0-min.js.gz"></script>
<script>
window.sessionReplay.init(AMPLITUDE_API_KEY, {
    deviceId: "<string>",
    sessionId: "<number>",
    sampleRate: "<number>"
    ...
 })
</script>
```

And then please follow the rest of the guidance on how to update the session id and grab the event properties in this documentation: https://amplitude.com/docs/session-replay/session-replay-standalone-sdk

**Comment by steverob** [comment]
@kwalker3690 thanks for your response. But it seems like `init` is not available on the `sessionReplay` object. 

![screen-grab-2024-07-04T19 54 19](https://github.com/amplitude/Amplitude-TypeScript/assets/1220480/c7e164fb-4b39-4b1a-a1d2-0e42059f0959)

**Comment by kwalker3690** [comment]
@steverob please check the comment above and confirm you have the matching script tag, it looks to me like you're still using the plugin script tag. You need to use the standalone script tag (it should not have the word 'plugin' in it)

**Comment by steverob** [comment]
Ahh thanks!

—
Steve Robinson
