### ISSUE TITLE
`@amplitude/plugin-session-replay-browser` does not support older Safari versions (<17)

### ISSUE THREAD

**Issue by markmssd** [amplitude/Amplitude-TypeScript#820]
## Expected Behavior
It should load on older Safari browsers too (<16)

## Current Behavior
It crashes with error
```
SyntaxError: Invalid regular expression: invalid group specifier name
```

Here's a related SO post: https://stackoverflow.com/questions/51568821/works-in-chrome-but-breaks-in-safari-invalid-regular-expression-invalid-group

## Possible Solution
Compile `rrweb` and `rrweb-snapshot` properly in `@amplitude/plugin-session-replay-browser` should fix the issue.

## Steps to Reproduce
Using `@amplitude/analytics-browser`, `@amplitude/plugin-web-attribution-browser`, or `@amplitude/experiment-js-client` causes no issues. When we use `@amplitude/plugin-session-replay-browser`, it causes the problem.

I boiled it down to the [amplitude/rrweb](https://github.com/amplitude/rrweb) dependency, which does not support [older browser versions](https://github.com/amplitude/rrweb/blob/master/package.json#L55-L58). You can see at https://browsersl.ist/#q=%22browserslist%22%3A+%5B%0A++%22defaults%22%2C%0A++%22not+op_mini+all%22%0A%5D that Safari <17 are not supported.

## Environment
- JS SDK Version: 2.9.3
- Installation Method: Yarn
- Browser and Version: Safari 16

**Comment by lewgordon-amplitude** [comment]
Hey @markmssd thanks for reporting this. We think we may have a fix for this and will be looking into this soon!

**Comment by markmssd** [comment]
Awesome thanks! Let me know if I can provide more details to help :)

**Comment by kwalker3690** [comment]
This has been fixed in the latest version!

**Comment by markmssd** [comment]
Thanks @kwalker3690 and @lewgordon-amplitude ! It's indeed working properly now. There is still the issue happening, around ~20x a day instead of thousands, but I personally can't reproduce anymore. I'm suspecting Ad Blockers blocking some scripts and causing this maybe?
