### ISSUE TITLE
@amplitude/session-replay-browser v 1.11.3 does not call shutdown()

### ISSUE THREAD

**Issue by GxDesign** [amplitude/Amplitude-TypeScript#822]
## Expected Behavior
Calling sessionReplay.shutdown() should stop recording

## Current Behavior
When running in debug mode, calling shutdown() logged the shutdown action in v1.9.4 (my previous version) and stopped the recording. In v1.11.3, nothing gets logged and the recording continues. I am using the segment wrapper.

Using the latest wrapper and session-replay-browser breaks shutdown functionality, reverting to wrapper version 0.1.0 and session-replay-browser v1.9.4 works.

## Steps to Reproduce

1. install @amplitude/session-replay-browser v1.11.3, and @amplitude/segment-session-replay-wrapper v0.3.1 (both latest)
2. Im using @segment/analytics-next v1.72.1 (latest)
```
const segment = new AnalyticsBrowser()
// 3. call action to load segment
const initSegment = () => segment.load({ writeKey: API_KEY })
// 4. call action to initialize SR wrapper, pass instance, API key etc
const initSRWrapper = () => setupAmpSRSegmentWrapper({  segmentInstance: segment, ... })
// 5. call action to shut down recording
const shutdownSR = () => sessionReplay.shutdown()


## Environment
- JS SDK Version: versions listed above
- Installation Method: Yarn
- Browser and Version: Chrome 126

**Comment by GxDesign** [comment]
Also, can we see the source code for the wrapper as we can for other packages? going to it from NPMjs returns a 404.

**Comment by lewgordon-amplitude** [comment]
Hey @GxDesign we're going to be looking at this relatively soon. Also we're planning on making the source code public today or early next week for the Segment wrapper.

**Comment by lewgordon-amplitude** [comment]
Okay just open source the repo. Check it out here: https://github.com/amplitude/segment-session-replay-wrapper

**Comment by lewgordon-amplitude** [comment]
Hey @GxDesign I'm curious about your setup. When I have something like this it does **NOT** work:

```js
import * as sessionReplay from "@amplitude/session-replay-browser";
import setupAmpSRSegmentWrapper from "@amplitude/segment-session-replay-wrapper";

const segment = `...`;
setupAmpSRSegmentWrapper({
  segmentInstance: segment,
  amplitudeApiKey: apiKey,
  sessionReplayOptions: {
    ...
  },
});

sessionReplay.shutdown();
```

But if I do this is does work!

```js
import * as sessionReplay from "@amplitude/segment-session-replay-wrapper/node_modules/@amplitude/session-replay-browser";
import setupAmpSRSegmentWrapper from "@amplitude/segment-session-replay-wrapper";

const segment = `...`;
setupAmpSRSegmentWrapper({
  segmentInstance: segment,
  amplitudeApiKey: apiKey,
  sessionReplayOptions: {
    ...
  },
});

sessionReplay.shutdown();
```

Just wanted to check this is not the same issue you're seeing before I dig further.

**Comment by GxDesign** [comment]
@lewgordon-amplitude the first is what I have.

**Comment by lewgordon-amplitude** [comment]
I wonder if the second works at all for you? I'm thinking overall the API could be better since I'd just except the first example to just work.

**Comment by GxDesign** [comment]
The second way works, I see the log saying the capturing stopped and then i see it restarted. I do keep seeing a lot of batch event logs I dont recall seeing before though: ```Amplitude Logger [Log]: Session replay event batch with seq id 1783 tracked successfully for session id``` Those continue about every 30-60 seconds even while inactive

**Comment by GxDesign** [comment]
Not to distract from the main issue of shutting down, but any idea why my sessions are also being duplicated? Not sure if its related: 
![Screenshot 2024-09-04 at 12 32 59 PM](https://github.com/user-attachments/assets/aef072cb-ca38-4604-9313-5e9514151032)

**Comment by lewgordon-amplitude** [comment]
Oh that's interesting. Maybe it explains part of it? I was thinking there's potentially two instances set up here. One when you pull the `@amplitude/session-replay-browser` and another when you pull the Segment wrapper.

**Comment by GxDesign** [comment]
Could you guide me on determining that? Im trying out the second implementation you presented and I still see the duplicate sessions.

**Comment by GxDesign** [comment]
This is my code, in short: 

```js 
import setupAmpSRSegmentWrapper from '@amplitude/segment-session-replay-wrapper'
import * as sessionReplay from '@amplitude/segment-session-replay-wrapper/node_modules/@amplitude/session-replay-browser'
import {AnalyticsBrowser} from '@segment/analytics-next'

const segment = new AnalyticsBrowser()

export const segmentSessionReplayInit = () => {
  if (environment.amplitudeKey) {
    void setupAmpSRSegmentWrapper({
      segmentInstance: segment,
      amplitudeApiKey: environment.amplitudeKey,
      sessionReplayOptions: {
        sampleRate: 1,
        privacyConfig: {
          defaultMaskLevel: 'conservative',
        },
        ...(environment.nodeEnv === 'development' ? SESSION_REPLAY_DEV_OPTIONS : {}),
      },
    })
  }
}

export const segmentSessionReplayShutdown = () => sessionReplay.shutdown()
```

**Comment by GxDesign** [comment]
Okay, Ive narrowed it down to an issue with how I restart the session replay, Im calling segmentSessionReplayInit again which I think registers a new plugin. When I stay on a route without shutting it down and restarting it (which occurs when entering restricted routes and returning to non-restricted), I get only one session recording.

**Comment by GxDesign** [comment]
Whats the correct way to restart the plugin?

**Comment by GxDesign** [comment]
@lewgordon-amplitude bumping. Ive tried calling sessionReplay.init with the import from the wrapper. Im still getting duplicate sessions and shutdown occasionally fails.

**Comment by GxDesign** [comment]
Ive tried a different route, where Im not calling shutdown but instead using an amp-block class to block excluded pages. It mostly works, except that when one of my pages makes an identify call and a redirect, the recording freezes up. I was able to resolve that by copying the wrapper locally and removing the logic in your identify handler, which wasnt present in v0.1.0. I am still getting duplicate sessions, especially if I refresh during a recording.

Could we schedule a call? My company is eager to release this.

**Comment by GxDesign** [comment]
Thanks, I've submitted a request and reached out to our assigned contact.

**Comment by lewgordon-amplitude** [comment]
Hey @GxDesign I'm going to close the issue for now since we'll be discussing this via an internal ticket.
