### ISSUE TITLE
Amplitude analytics-browser 2.11.0 with autocapture: true freezes on click on dropdown menu 

### ISSUE THREAD

**Issue by mjsilva** [amplitude/Amplitude-TypeScript#861]
## Expected Behavior
Not freeze and capture the interaction

## Current Behavior
We recently upgraded from:
```
    "@amplitude/analytics-browser": "^2.9.3",
    "@amplitude/plugin-session-replay-browser": "^1.6.5",
```
to
```
    "@amplitude/analytics-browser": "^2.11.0",
    "@amplitude/plugin-session-replay-browser": "^1.6.21",
```

and enabled `autocapture`. But it broken one of our dropdown menu select and had to revert back to previous version. Essentially when a user clicked on a dropdown menu it would just freeze any interaction like JS thread was in an infinite loop. Does anyone else had this problem?

## Possible Solution
downgrade to ^2.9.3

## Steps to Reproduce
I haven't tried to reproduce it on a clean repo with just amplitude enabled as that's a lot of work. Just trying to understand if anyone else is having this issue. Can do further digging if needed.

## Environment
- SDK Version: mentioned above
- Node version: v20.13.1
- Chromium Engine Version 127.0.6533.120

**Comment by izaaz** [comment]
@mjsilva - A similar issue was fixed in 2.11.1. Can you please try that version of the SDK to see if it resolves your problem?
