### ISSUE TITLE
React native Session Replay

### ISSUE THREAD

**Issue by RouberR** [amplitude/Amplitude-TypeScript#872]
I'm currently using @amplitude/analytics-react-native for analytics in my React Native application and I'm interested in integrating Session Replay to capture user interactions. However, I couldn't find any documentation or library related to Session Replay for react-native or similar functionality for React Native. Is Session Replay available for React Native apps? If not, is there any workaround or plan to support this feature in the future? Any guidance on how to achieve similar functionality in React Native would be appreciated.

**Comment by izaaz** [comment]
@RouberR - we currently don't support session replay for react native though its on our radar to add support for RN. We don't have a timeline for this yet.

**Comment by RouberR** [comment]
@izaaz Thanks, we will wait for support of this function

**Comment by izaaz** [comment]
@RouberR - we have a plugin that is currently in Beta stage. Please feel free to give this a try and share any feedback that you have. You can use this repository to create any issues that you notice in this plugin

https://www.npmjs.com/package/@amplitude/plugin-session-replay-react-native
