### ISSUE TITLE
Unable to set event-level groups

### ISSUE THREAD

**Issue by gesposito** [amplitude/Amplitude-TypeScript#88]
## Expected Behavior
[EventOptions](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/base-event.ts#L10) parameter in `logEvent` allows for  a [groups](https://github.com/amplitude/Amplitude-TypeScript/blob/main/packages/analytics-types/src/base-event.ts#L7) key

## Current Behavior
`groups` (event-level groups) cannot be set with `logEvent`:
```ts
logEvent(eventType, eventProperties, { groups?: { [key: string]: any } })
```

## Steps to Reproduce
I'm trying to match the `amplitude-js` [logEventWithGroups](https://github.com/amplitude/Amplitude-JavaScript/blob/main/src/amplitude-client.js#L1611) API that has support for
```ts
logEventWithGroups(eventType, eventProperties, groups)
```
https://github.com/amplitude/Amplitude-JavaScript/blob/main/src/amplitude-client.js#L1406

## Environment
- JS SDK Version: 0.3.1
- Installation Method: npm

**Comment by kevinpagtakhan** [comment]
@gesposito thanks for submitting an issue! Thanks for your patience as we continuously iterate on this new SDK. This is unintended behavior and we will work on addressing this issue.
