### ISSUE TITLE
TS1005 Error amplitude/analytics-types/element-interaction.ts:70:39 ? expected  During Angular build amplitude/analytics-browser version 2.9.3

### ISSUE THREAD

**Issue by RakeshrajA5** [amplitude/Amplitude-TypeScript#883]
TS1005 Error amplitude/analytics-types/element-interaction.ts:70:39 ? expected  During Angular build amplitude/analytics-browser version 2.9.3

**Comment by izaaz** [comment]
@RakeshrajA5 can you please try with the latest version to see if it solves the problem?

**Comment by Mercy811** [comment]
Hi @RakeshrajA5, is it the same issue as https://github.com/amplitude/Amplitude-TypeScript/issues/882? Could you run `yarn list @amplitude/analytics-types` in your project and share the screenshot? Thanks

**Comment by Abde-T** [comment]
Getting the same error.
```
Error: node_modules/@amplitude/analytics-types/lib/esm/element-interactions.d.ts:70:64 - error TS1005: '?' expected.
Element: infer T extends abstract new (...args: any) => any;
```

running `npm install @amplitude/analytics-types` results in a successful build, but the error still occurs when starting the development server, or on the Netlify build.

**Comment by AyoubTRD** [comment]
@izaaz @Mercy811 We have the same issue while building our Angular app

**Comment by milingo** [comment]
Same error running on Next.js:

![migueljimenez@MJ0292~codecobeedashboard-2 0 2024-10-02 at 12 11 42 PM](https://github.com/user-attachments/assets/74abbab1-8b95-4229-9ca1-949a19655e2b)

**Comment by Mercy811** [comment]
analytics-browser 2.11.8 and analytics-types 2.8.3 should fix it
