### ISSUE TITLE
Fails to build on RN 0.76

### ISSUE THREAD

**Issue by johnf** [amplitude/Amplitude-TypeScript#901]
## Expected Behavior

Package should build succesfully

## Current Behavior

> Task :amplitude_analytics-react-native:compileDebugKotlin FAILED
e: file:///home/johnf/work/gladly/mobile/node_modules/@amplitude/analytics-react-native/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt:64:25 Type mismatch: inferred type is String? but String was expected

## Possible Solution

```diff
diff --git a/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt b/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
index cfe7bcab8600fcfdf5d8dd77aeb4ba68ac0a8100..93f2101121cf7e69878f7faeb09ba0e298b9812e 100644
--- a/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
+++ b/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
@@ -55,7 +55,7 @@ class LegacyDatabaseStorage(context: Context, databaseName: String) : SQLiteOpen
 
     private fun queryDb(
         db: SQLiteDatabase,
-        table: String?,
+        table: String,
         columns: Array<String?>?,
         selection: String?,
         selectionArgs: Array<String?>?,
```

## Steps to Reproduce
Standard steps to add @amplitude/analytics-react-native to your project

## Environment
- JS SDK Version: 1.4.10
- Installation Method: yarn
- Browser and Version:  React Native 0.76

## Other

As a side note is this package built from this repo? I tried to do a PR but the file in question doesn't exist

**Comment by MonikaGupta756** [comment]
I am facing the same issue but with RN 0.73.6

**Comment by huextrat** [comment]
This is on Kotlin SDK, here is a proposal to fix it: https://github.com/amplitude/Amplitude-Kotlin/pull/228

**Comment by izaaz** [comment]
The RN SDK does not use the kotlin SDK underneath. This is the file that needs to be changed

https://github.com/amplitude/Amplitude-TypeScript/blob/v1.x/packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt

But I wonder why its failing now though? Its been like this for a long time. Do y'all use a stricter type checking that makes this fail?

**Comment by huextrat** [comment]
> The RN SDK does not use the kotlin SDK underneath. This is the file that needs to be changed
> 
> 
> 
> https://github.com/amplitude/Amplitude-TypeScript/blob/v1.x/packages/analytics-react-native/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
> 
> 
> 
> But I wonder why its failing now though? Its been like this for a long time. Do y'all use a stricter type checking that makes this fail?

@izaaz Ah, good point, we'll have to patch this version with the fix then.

This issue has only existed since version 0.76 of RN, probably due to a change in compatibility with Kotlin

**Comment by younes0** [comment]
@johnf there's a missing change fyi

```diff
diff --git a/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt b/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
index cfe7bcab8600fcfdf5d8dd77aeb4ba68ac0a8100..9f54fd283f079629ee0eed735d007c83236c43fc 100644
--- a/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
+++ b/android/src/main/java/com/amplitude/reactnative/LegacyDatabaseStorage.kt
@@ -59,7 +59,7 @@ class LegacyDatabaseStorage(context: Context, databaseName: String) : SQLiteOpen
         columns: Array<String?>?,
         selection: String?,
         selectionArgs: Array<String?>?,
-        orderBy: String?,
+        orderBy: String,
     ): Cursor? {
         return db.query(table, columns, selection, selectionArgs, null, null, orderBy, null)
     }
@@ -225,7 +225,7 @@ class LegacyDatabaseStorage(context: Context, databaseName: String) : SQLiteOpen
                 ),
                 DatabaseConstants.KEY_FIELD + " = ?",
                 arrayOf(key),
-                null,
+                DatabaseConstants.ID_FIELD + " ASC",
             )
             if (cursor!!.moveToFirst()) {
                 value = if (table == DatabaseConstants.STORE_TABLE_NAME) cursor.getString(1) else cursor.getLong(1)

**Comment by dpyeates** [comment]
any update on this change getting added please?

**Comment by younes0** [comment]
It seems surprising that Amplitude isn't being very responsive about their React Native SDK (this issue, new architecture...)

This appears particularly noteworthy given React Native's growing popularity among major apps and companies. 
One has to wonder if Amplitude's Product Managers are aware of this situation. https://reactnative.dev/showcase

**Comment by khomchyk** [comment]
> It seems surprising that Amplitude isn't being very responsive about their React Native SDK (this issue, new architecture...)
> 
> This appears particularly noteworthy given React Native's growing popularity among major apps and companies. One has to wonder if Amplitude's Product Managers are aware of this situation. https://reactnative.dev/showcase

++
A week to merge an one-line fix seems like an unusually relaxed timeline for resolving an issue that's completely blocking Android functionality on the latest production React Native version, especially from a market leader in analytics.

**Comment by izaaz** [comment]
Apologies for the delay folks.

Here's the [PR](https://github.com/amplitude/Amplitude-TypeScript/pull/912).

It looks like this issue only happens when the compileSdk version is set to 35.

**Comment by izaaz** [comment]
@huextrat - Thanks for the fix on the kotlin SDK too. It starts throwing an error when I set the compile SDK version to 35 so i'll merge that PR as well.

**Comment by izaaz** [comment]
@johnf can you please try version 1.4.11?

**Comment by johnf** [comment]
@izaaz looks good
