### ISSUE TITLE
Latitude and Longitude always empty

### ISSUE THREAD

**Issue by dusugen** [amplitude/Amplitude-TypeScript#908]
@amplitude/analytics-react-native : "^1.4.10",
"react-native": "0.72.7",

I want to have actual user position. Amplitude understand where i am, but doesn't provide Latitude and Longitude.
How can I enable it ?
<img width="389" alt="image" src="https://github.com/user-attachments/assets/a71c3271-e9e4-4dea-8625-ed37bf680e95">

This is how I initialize :

```
{ init } from '@amplitude/analytics-react-native';

export const initializeAmplitude = (amplitudeKey?: string) => {
  if (amplitudeKey) {
    try {
      init(amplitudeKey);
    } catch (error) {
      console.log(error);
    }
  }
};
```
I tried to search COPPA setting from [docs](https://amplitude.com/docs/sdks/analytics/react-native/migrate-to-the-latest-react-native-sdk#coppa) , but no settings available to watch location.

I understand that I can use custom userProperties, but I want to know if it possible to get it automatically.

**Comment by Mercy811** [comment]
Hi @dusugen, you can follow the doc to set location https://amplitude.com/docs/sdks/analytics/react-native/react-native-sdk#location
