### ISSUE TITLE
TypeError: plugin is undefined

### ISSUE THREAD

**Issue by zherr** [amplitude/Amplitude-TypeScript#916]
## Expected Behavior
When calling `amplitude.remove("plugin-name")`, but the plugin does not exist, an exception should not be raised.

## Current Behavior
```
Source
Timeline.prototype.deregister/</<
node_modules/@amplitude/analytics-browser/node_modules/@amplitude/analytics-core/lib/esm/timeline.js (49:1)
step
node_modules/tslib/tslib.es6.mjs (147:1)
verb/<
node_modules/tslib/tslib.es6.mjs (128:44)
__awaiter/<
node_modules/tslib/tslib.es6.mjs (121:1)
__awaiter
node_modules/tslib/tslib.es6.mjs (117:1)
Timeline.prototype.deregister
node_modules/@amplitude/analytics-browser/node_modules/@amplitude/analytics-core/lib/esm/timeline.js (41:25)
AmplitudeCore.prototype._removePlugin
node_modules/@amplitude/analytics-browser/node_modules/@amplitude/analytics-core/lib/esm/core-client.js (124:29)
AmplitudeCore.prototype.remove
node_modules/@amplitude/analytics-browser/node_modules/@amplitude/analytics-core/lib/esm/core-client.js (121:1)
debugWrapper/<
node_modules/@amplitude/analytics-browser/node_modules/@amplitude/analytics-core/lib/esm/utils/debug.js (76:1)
```

## Possible Solution
Currently handling / ignoring this error with:
```
const result = amplitude.remove(plugin.name);
result.promise.catch((error) => {
  console.warn('Amplitude - Warn: ', error);
});
```
But it would seem there's a deeper handling issue going on here.

It would be very convenient to users of this SDK to be able to "reset" or at least list the plugins currently installed via a new method:
```
amplitude.listPlugins() // returns a list of plugin names currently added
```

## Steps to Reproduce
Call `amplitude.remove(...)` with a random plugin name.

## Environment
```
"@amplitude/analytics-browser": "^2.11.7",
```

**Comment by Mercy811** [comment]
Hi @zherr, thanks for choosing Amplitude. Catch the error of removing a non-existing plugin should be the right workaround. Adding `amplitude.listPlugins()` is a feature request. We will put this into our backlog and update here once it's implemented.

**Comment by zherr** [comment]
Thank you @Mercy811 !

Do you track these features in GitHub as well? Do you have a link where I could see this backlogged item?

**Comment by Mercy811** [comment]
Hi @zherr, we track them in Jira backlong but we will update here. We currently didn't it a high priority because even though `amplitude.listPlugins()` is added `amplitude.remove()` should still throw an error as it's possible to remove a plugin which is not installed.

**Comment by Mercy811** [comment]
Hi @zherr, the SDK now will warn if plugin doesn't exist by https://github.com/amplitude/Amplitude-TypeScript/pull/936

**Comment by zherr** [comment]
Thank you, @Mercy811

**Comment by huv1k** [comment]
Is there any update on `listPlugins`? 😅 I would love to remove some plugins in nested instances 🙈
